### PR TITLE
Carousel added 

### PR DESCRIPTION
**Pull request by nikhilagastya**
1. I added the Carousel to the bottom of the Organizations page.
2.Made the carousel using swiper component 
3.Initially the position is at the bottom right of the page which can be set after rectifying #129

### CODE REVIEW

**Comment by andrewtavis** [comment]
FYI @nikhilagastya, plan is to get to this review after I merge a few more that came in beforehand, but should be done in the next few days :)

**Comment by nikhilagastya** [comment]
alright @andrewtavis , I am also updating the screenshot for your ref , lmk if u need something else 
Screenshot 2023-05-18 230030

**Comment by andrewtavis** [comment]
Thanks for sending along the image, @nikhilagastya! Just checked out the deployment preview above as well :) All looks really great functionality wise, but there are some comments:

- It’d be good if the left and right chevrons were on the images themselves rather than to the side
- The corners of the “images” should be rounded
- Ideally we’d also have the dots in the bottom center of the images that then indicate how many images there are and which one is currently being displayed (one at the index of the displayed image is full alpha and the others have a lower alpha value for a bit of transparency)

Aside from above I think we’re good to go 😊😊 How does all this sound? Let me know if you need any support! Really great to get be getting this component up and running :)

**Comment by andrewtavis** [comment]
Just checked the preview, @nikhilagastya! Looks wonderful and everything seems to be working great 😊 Do you plan on rounding the corners or should I take it from here? Thanks so much for such a significant first contribution!

**Comment by nikhilagastya** [comment]
Hey @andrewtavis  I have made the changes you asked for ,kindly review it .

**Comment by nikhilagastya** [comment]
hey @andrewtavis i have updated it accordingly. kindly do check it 
Screenshot 2023-05-20 004325

**Comment by nikhilagastya** [comment]
hey @andrewtavis is this all good, the corners have been rounded

**Comment by andrewtavis** [comment]
Hey @nikhilagastya 👋 I've had myself a very busy weekend. Need to finish writing some issues for another project now, but will hopefully be able to review later today. Thanks!

**Review by andrewtavis — APPROVED** [review]
All looks good, @nikhilagastya! Thanks for your patience and your willingness to react to feedback with quick edits 🙏 Hope you continue to contribute to activist in the future 😊 There will be lots of issues being made in the coming weeks as we onboard some more people from an external team, so keep up to date on GitHub or in the [Matrix chat rooms](https://matrix.to/#/#activist_community:matrix.org).

**Pull request merged**
