### PR TITLE
Fix #579: Add shadow to sidebar footer when content is scrollable

### LINKED ISSUE #579: Add top shadow to sidebar footer when content expands below
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a check to the [sidebar footer](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftFooter.vue) for when the content of the [sidebar index](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftIndex.vue) or the [sidebar filters](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftFilters.vue) is scrollable, and if that is the case then we'll want a slight top shadow to be added to the sidebar footer such that it appears over the content.

The shadow should be `shadow-sm shadow-zinc-700`, but we'll need to make sure it's only at the top :)

### Contribution

Happy to support someone on this or get to it eventually myself! This is a great `good first issue` for new contributors, and those already in the community are also welcome to pick it up 😊

### PR DESCRIPTION
**Pull request by PustakP**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request addresses issue #579 by implementing a shadow effect on the sidebar footer when the content of the sidebar (either index or filters) is scrollable.

### Changes made:

1. Updated `SidebarLeftFooter.vue` to accept a new prop `contentIsScrollable` and apply a shadow when it's true.
2. Modified `SidebarLeftIndex.vue` and `SidebarLeftFilters.vue` to detect when their content is scrollable and emit this information.
3. Updated the parent component `SidebarLeft.vue` to pass the scrollable state from the index and filters components to the footer component.

### Additional notes:

The changes primarily affect the following components:
- `SidebarLeftFooter.vue`
- `SidebarLeftIndex.vue`
- `SidebarLeftFilters.vue`
- `SidebarLeft.vue`

### Related issue

- #579

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @PustakP 👋 Could you take a screenshot of the change you made and send it along? Also, if you'd like to work on the [linting errors](https://github.com/activist-org/activist/actions/runs/9711510877/job/26845648212?pr=910), let me know! Can also handle them for you if you'd prefer 😊

**Comment by andrewtavis** [comment]
I can also take care of the merge conflict as well. No stress 😎

**Comment by PustakP** [comment]
@andrewtavis Hi! Thank you for your response, super excited for this. I'll be out of town for a few days so I can't send through a screenshot right now, but I can start on the merge conflicts as soon as Tuesday. Thanks!

**Comment by andrewtavis** [comment]
Thank you, @PustakP! Looking forward to working on this with you further :)

**Comment by andrewtavis** [comment]
Hey @PustakP 👋 Checking in on this again :) Would be great to get a screenshot of the change that this is sending along. Also happy to do a quick call at some point if that would be helpful!

**Comment by andrewtavis** [comment]
Hey @PustakP 👋 Closing this out :) Please feel free to send along another PR :) It would be great to get a screenshot of the change involved, if you choose to open a new one 😊

**Pull request closed without merging**
