### PR TITLE
Use page object pattern for e2e tests

### PR DESCRIPTION
**Pull request by cquinn540**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](CONTRIBUTING.md#testing)

---

### Description

This change adds tests for the landing, home, and sign-in pages, and it updates the playwright tests to use the page object patternbased on the work of @aasimsyed 

I also changed the test directory from `tests` to `test-e2e` to better differentiate it from our component tests, as well as some various bug fixes.

### Related issue

- #432

### CODE REVIEW

**Comment by cquinn540** [comment]
Great I'm running into the `$t` not defined issue now

**Comment by mattburnett-repo** [comment]
Hi Colin,

Looking at the log for the PR Frontend Checks, I see only the following errors:
```
Error: test-e2e/component-objects/EventMenu.ts(68,18): error TS2571: Object is of type 'unknown'.
Error: test-e2e/component-objects/EventMenu.ts(75,19): error TS2571: Object is of type 'unknown'.
Error:  Command failed with exit code 2: /home/runner/work/activist/activist/frontend/node_modules/vue-tsc/bin/vue-tsc.js --noEmit
```
While it's never a fun time to hit a snag like this, it looks like this is a relatively straight-forward typing error involving EventMenu.ts, in one of the e2e tests. The $t issue is / was something else, and it doesn't look like it appears in the Frontend Checks log.

Could you please reply here and let me know if you're running into $t errors? Specifically, it would be helpful to know where you are finding them.

Also, please keep in mind that the $t issue doesn't look like it has any negative functional or performative effects, meaning that it doesn't appear to have any real-time, production-related effects on the app. I've been pursuing it simply because I make a point of chasing down these sorts of oddball system messages. That means, don't stress on the $t thing too much :)

Thanks for all of the great work!

**Comment by cquinn540** [comment]
> Error: test-e2e/component-objects/EventMenu.ts(68,18): error TS2571: Object is of type 'unknown'.
> Error: test-e2e/component-objects/EventMenu.ts(75,19): error TS2571: Object is of type 'unknown'.

@mattburnett-repo Just resolved these two errors...sort of.  They are the result of what I would consider to be an anti-pattern with inheritance in the branch I took over.

Currently the code is functional, but IMO it is not maintainable.  I plan on making it more maintainable as my next issue, but I expect that to take a significant amount of time, and I don't think we want the project to go without the new test coverage for that long.

**Comment by cquinn540** [comment]
For the `$t` related errors, this is caused both by having a messed up `yarn.lock` file and having nuxt improperly installed.

What I had to do was:

1. Replace my `yarn.lock` file with the one in main
2. I ran `yarn cache clean` (this clears the yarn cache system wide and takes a long time, and I'm not sure it it's 100% necessary yet)
3. Delete my `node_modules` folder
4. Load environment variables into my shell
```bash
set -a && source ../.env.dev && set +a
```
5. Run `yarn install`

If you look in `package.json` you will see there is a postinstall step the runs `nuxt prepare`.  Nuxt prepare sets up all the typescript magic nuxt does for auto-imports.  I think the i18n plugin needs the dev environment variables set for its types to set up properly.

**Comment by andrewtavis** [comment]
This is really great that we've found a workable solution here, @cquinn540! Do we want to document this somewhere in the contributing guide? :)

**Comment by cquinn540** [comment]
I can document how to run it, but I think it needs to be refactored before adding a guide on how to contribute to the e2e tests.

**Comment by cquinn540** [comment]
Or if you mean the `$t` type issue yeah that should be documented in the contributing guide but I think that should be a different PR attached to the issue raised for it.  This PR is big enough as it is.

**Comment by mattburnett-repo** [comment]
FWIW, I tried the five steps you mentioned above, and still get the $t issue.

Re-enabling the vue-i18n.d.ts file makes the $t issue go away.

Please let me know when you find an explanation / solution for this. Very curious to see how this can be resolved.

**Comment by andrewtavis** [comment]
I'll put the directions for the i18n file back in the contributing guide :)

**Comment by andrewtavis** [comment]
Ok so post a yarn outage we're passing in frontend, but still failing in e2e. Here are the failed tests:

```bash
    [chromium] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [chromium] › landing-page.spec.ts:118:7 › Landing Page › Landing Page has no detectable accessibility issues 
    [chromium] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [chromium] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [webkit] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [webkit] › landing-page.spec.ts:118:7 › Landing Page › Landing Page has no detectable accessibility issues 
    [webkit] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [webkit] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [Mobile Chrome] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [Mobile Chrome] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [Mobile Chrome] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [Mobile Safari] › home-page.spec.ts:31:7 › Home Page › Navigation links should be functional ───
    [Mobile Safari] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [Mobile Safari] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [Mobile Safari] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [Mobile Samsung] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [Mobile Samsung] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [Mobile Samsung] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [Mobile iPad Portrait] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [Mobile iPad Portrait] › landing-page.spec.ts:118:7 › Landing Page › Landing Page has no detectable accessibility issues 
    [Mobile iPad Portrait] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [Mobile iPad Portrait] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
    [Mobile iPad Landscape] › home-page.spec.ts:74:7 › Home Page › Home Page has no detectable accessibility issues 
    [Mobile iPad Landscape] › landing-page.spec.ts:118:7 › Landing Page › Landing Page has no detectable accessibility issues 
    [Mobile iPad Landscape] › sign-in-page.spec.ts:100:7 › Sign In Page › should show error for invalid credentials 
    [Mobile iPad Landscape] › sign-in-page.spec.ts:111:7 › Sign In Page › Sign In Page has no detectable accessibility issues 
```

We can look into these in the future :)

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the work to bring all of this in, @cquinn540! Looking forward to the further steps to bring all this up to Playwright standards 😊

**Pull request merged**
