### PR TITLE
create sidebar right component

### PR DESCRIPTION
**Pull request by Mradosi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Create sidebar right component, instead of meatball

### Related issue

- #201

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Minor comments on this PR, @Mradosi :) Thanks so much for the work here! Really turned out well, and initial accessibility tests also show that this is all working really nicely 😊

- Firstly some of the component names need to be switched so that the component class name is within the name of the component (i.e. `SidebarLeft/SidebarLeft.vue`)
  - Do we want to maybe do a parent `Sidebar` directory and then have `SidebarLeft` and `SidebarRight` inside of it? Not sure if that would be better 🤔
  - Regardless we need some renaming for left sidebar components 😊
- No stress as you didn't have designs to work from, but could we remove the background from the hamburger menu so it's all a bit more clean
- Could we also get the `MenuMobileHeader` back for breakpoints below `sm` and add in the hamburger menu to that? rather than using the website header?

I think we should be good to merge from there! I'll likely play around with the animation a bit post merging as the current version's a bit too involved. We could also discuss this if you had interest in implementing it yourself :)

Thanks again! Really wonderful having this level of feature creation being possible from the team 😊 Really is taking a load off my shoulders 🙏

**Comment by Mradosi** [comment]
> Minor comments on this PR, @Mradosi :) Thanks so much for the work here! Really turned out well, and initial accessibility tests also show that this is all working really nicely 😊
> 
> * Firstly some of the component names need to be switched so that the component class name is within the name of the component (i.e. `SidebarLeft/SidebarLeft.vue`)
>   
>   * Do we want to maybe do a parent `Sidebar` directory and then have `SidebarLeft` and `SidebarRight` inside of it? Not sure if that would be better 🤔
>   * Regardless we need some renaming for left sidebar components 😊
> * No stress as you didn't have designs to work from, but could we remove the background from the hamburger menu so it's all a bit more clean
> * Could we also get the `MenuMobileHeader` back for breakpoints below `sm` and add in the hamburger menu to that? rather than using the website header?

Tomorrow  I will implement this changes :)
> I think we should be good to merge from there! I'll likely play around with the animation a bit post merging as the current version's a bit too involved. We could also discuss this if you had interest in implementing it yourself :)
> 

Sure, I would be more than happy to work on the animation - do you already have a preliminary concept for it?

**Comment by andrewtavis** [comment]
> Tomorrow I will implement this changes :)

Looking forward, @Mradosi! 🙌

> Sure, I would be more than happy to work on the animation - do you already have a preliminary concept for it?

Good question :D After taking a look I think that something simple like the third one on [this codepen](https://codepen.io/designcouch/pen/ExvwPY) would be good. What do you think? Also happy if you have other suggestions!

**Comment by andrewtavis** [comment]
Really appreciate the quick fixes, @Mradosi :) :) Looking forward to checking it all out 😊

**Comment by andrewtavis** [comment]
@Mradosi, would it be possible for you to solve these merge conflicts in another commit? I've been looking into this for a bit now and I'm a bit at a loss for how to do this properly... Any explanation you could provide for how to do it properly would be really appreciated as we're running into this more and more these days.

**Comment by andrewtavis** [comment]
Generally the directions I'm getting from GitHub are the following:

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b Mradosi-mradosi/feature/sidebar-right main
git pull https://github.com/Mradosi/activist.git mradosi/feature/sidebar-right

Step 2: Merge the changes and update on GitHub.

git checkout main
git merge --no-ff Mradosi-mradosi/feature/sidebar-right
git push origin main
```

What this looks like is that at the end I'm just going to make a commit to main with the changes here instead of fixing the issue in the branch and then merging 🤔

**Comment by andrewtavis** [comment]
Or would `git merge --no-ff Mradosi-mradosi/feature/sidebar-right` merge this PR and thus close it? Sorry, I'm starting to realize that I've been a bit too reliant on the GitHub UI for git related processes...

**Review by andrewtavis — APPROVED** [review]
@Mradosi, I'm really not sure what happened here... Sorry that this is such a mess 🤦‍♂️ Seems like the changes coming through were now already committed as I merged them directly into main. I'm going to continue to experiment with the using VS Code for code review and hopefully this will go smoother in the future.

**Pull request merged**
