### PR TITLE
updated/added shadow to cards

### PR DESCRIPTION
**Pull request by Vidhanvyrs**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #254

### CODE REVIEW

**Comment by Vidhanvyrs** [comment]
please review the commited changes and give me feedback if improvement needed

**Comment by andrewtavis** [comment]
Thank you, @Vidhanvyrs! I'll try to get to this tonight 😊

**Comment by andrewtavis** [comment]
Looking at this, @Vidhanvyrs, could we do `shadow-sm` instead? I think that a bit more subtle of a shadow would be better in this case :) Aside from that, all's great! Thanks so much :)

**Comment by Vidhanvyrs** [comment]
Absolutely, if you'd like a more subtle shadow, we can use shadow-sm instead 
ON IT!

**Review by andrewtavis — APPROVED** [review]
Thanks for the quick reaction, @Vidhanvyrs! Appreciate the work here and hope you contribute again in the future!

**Pull request merged**
