### PR TITLE
Feed card component #142

### PR DESCRIPTION
**Pull request by momanyisamuel**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

- added feed card component
- added get involved component with feeds and events options

### Related issue

- #142
- #145

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Minor minor changes, @momanyisamuel:

- There's a border around the organization name and icon that's not needed.
- The text generally can be smaller — same size as the base text :)
- We need the dark mode Tailwind `dark:` colors to also be added 🌙 

Happy to merge once the above is fixed. Looking

**Comment by andrewtavis** [comment]
Ah you're doing both issues in this PR 😊 Great! Hope I didn't jump in to quickly :)

**Comment by andrewtavis** [comment]
Looking at it again right before I pass out, @momanyisamuel :) All looks great. We're just missing some dark mode coloration as I mentioned [above](https://github.com/activist-org/activist/pull/145#pullrequestreview-1431679408) :)

**Comment by andrewtavis** [comment]
Minor merge to fix the fact that the home page now has an example of the event icon on it as well :)

**Comment by momanyisamuel** [comment]
Hi @andrewtavis I was wondering about the typography sizes?? so i used the `responsive-text-0 & responsive-text-1` custom tailwind classes respectively for the feed card to keep consistency. May i suggest we rename them according to typography sizes 
i.e. `h1, h2 ...`  or `base, sm, lg ...`  so that we easily identify and reuse them as we do for the padding classes?? not sure what you think of this

**Comment by andrewtavis** [comment]
My thought process on renaming the responsive text classes was to keep consistency with Tailwind enumeration, @momanyisamuel :) Definitely open to discussion though! I honestly just felt a bit weird choosing something that’s `1` for large within a Tailwind context where larger numbers are always larger styles. Was planning on renaming the responsive text classes as well once we clear some the the current PRs and iterating them all up by one as I made `responsive-text-0` because `responsive-text-1` wasn’t small enough. 

Lemme know what you think :) Maybe the happy medium is `xs`, `s`, etc?

**Comment by momanyisamuel** [comment]
@andrewtavis i think we can keep using the responsive classes as they are not a problem.

**Comment by andrewtavis** [comment]
I'll still do the rename once it's all merged to make sure we're starting with `1`. Am actually working on the `STYLE_GUIDE.md` file for #157 right now :)

**Review by andrewtavis — APPROVED** [review]
All's looking good, @momanyisamuel! Thanks for these commits 😊 Appreciate your continued work on activist! We weren't able to do a call during the Code Night, but let's look to do one soon :) :)

**Comment by momanyisamuel** [comment]
glad this worked out @andrewtavis no worries just glad i could assist.

**Pull request merged**
