### PR TITLE
#685/feature update default to walking map directions api

### PR DESCRIPTION
**Pull request by GrandSuccess87**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

The purpose of this merge request is to set the default map directions to walking.

I tested this manually in my local environment and referenced the [Map Libre Documentation](https://maplibre.org/maplibre-gl-directions/#/examples/multiple-profiles) to confirm the color for the route aligns with the by "foot" profile vs driving.

### Related issue

- #673 
- #718

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @GrandSuccess87! Seems to not be working :( Going to [deploy-preview-778--activist-org.netlify.app/en/events/123/about](https://deploy-preview-778--activist-org.netlify.app/en/events/123/about), if I click around and try to go through the park it's still giving driving directions. Maybe I'm misunderstanding though! On the demo though we could go over the walking paths.

**Comment by GrandSuccess87** [comment]
> Hey @GrandSuccess87! Seems to not be working :( Going to [deploy-preview-778--activist-org.netlify.app/en/events/123/about](https://deploy-preview-778--activist-org.netlify.app/en/events/123/about), if I click around and try to go through the park it's still giving driving directions. Maybe I'm misunderstanding though! On the demo though we could go over the walking paths.

Ohh noo :(( I'll have to see why it's only working locally. I'll aim to take another look tomorrow, if not Monday at the latest!

**Comment by GrandSuccess87** [comment]
Maybe the Deploy Preview is experiencing some lag?

**Comment by andrewtavis** [comment]
So it was working for you that you could do directions through the park?

**Comment by GrandSuccess87** [comment]
Yeah it's working for me. But just to confirm I understood, can you point me to the Figma for the desired outcome?

**Comment by andrewtavis** [comment]
Lemme send along some screenshots, @GrandSuccess87 :)

This is me trying to set a route in the deployment preview:

Screenshot_2024-03-23 23 46 16

And this is a similar route using the [OSRM demo mentioned in the issue](https://map.project-osrm.org/):
Screenshot_2024-03-23 23 47 41

Ideally it would take us through the park, but we're instead routed through the streets :)

**Comment by GrandSuccess87** [comment]
Ah! Okay, I thought checked out all the links in the issue. I'll get this updated

**Comment by andrewtavis** [comment]
Thanks @GrandSuccess87! 😊😊

**Comment by GrandSuccess87** [comment]
I've been out of town for the holiday, but I will work on this more this weekend!

**Comment by andrewtavis** [comment]
No stress, @GrandSuccess87! Looking forward to the next steps :)

**Review by andrewtavis — APPROVED** [review]
Hey @GrandSuccess87! Sorry for the bother here. I'm realizing that this is actually fine in that it seems that driving directions are the only ones that allow for user interactivity right now :) Source for this is the [profiles documentation for the extension](https://maplibre.org/maplibre-gl-directions/#/examples/multiple-profiles) where it says: `Note that interactivity is not supported for multiple profiles`. We're doing exactly what we're supposed to do, but the issue is that for walking and biking it's supposed to be receiving data and setting a predefined path, whereas we want interactivity. I'll send along a commit with the other profiles in there after this. You'll see that we actually are successfully changing the profile in that walk is blue, bike is teal and drive is purple based on what you comment out. Issue is that it doesn't change regardless, so I figure it's just not implemented for walk and bike now.

Let's set it to walk and hopefully the dependency will get there at some point!

Thanks for all of this, and hope you have a great weekend!

**Pull request merged**
