### PR TITLE
Tests for the password reset endpoints

### PR DESCRIPTION
**Pull request by thesarfo**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This pull request proposes to add comprehensive tests for the password reset functionality in the authentication app. It aims to ensure that the password reset process works correctly and handles various scenarios properly.

#### Changes:
* Password Reset Email: Adds a test to verify that a password reset email is sent successfully to the registered user's email address.
* Invalid Email Handling: Adds a test to ensure that an error is returned when attempting to reset the password with an invalid email address.
* Successful Password Reset: Adds a test to confirm that the password reset process works correctly when a valid verification code is provided.
* Invalid Verification Code Handling: Adds a test to ensure that an error is returned when attempting to reset the password with an invalid verification code.

The changes were tested using Django's test client to simulate the various scenarios and assert the expected outcomes. The tests cover both positive and negative cases to ensure the robustness of the password reset feature.
### Related issue

- #ISSUE_NUMBER
https://github.com/activist-org/activist/issues/898

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for sending this along, @thesarfo! We'll check it and get back with feedback as soon as we can :)

**Comment by to-sta** [comment]
@thesarfo thanks for your PR 🚀 . I fixed a few minor details and ran the tests successfully.

**Review by to-sta — APPROVED** [review]

**Comment by andrewtavis** [comment]
Thanks for the work here, @thesarfo! Give me just a moment to send along some changes, and then I'll take care of any merge conflicts in here. Should be in by the start of the weekend 😊

**Comment by thesarfo** [comment]
sure thing, thanks😊

**Review by andrewtavis — APPROVED** [review]
Thanks again for all the work here and your patience, @thesarfo! Hope to work with you again soon! 😊

**Comment by thesarfo** [comment]
@andrewtavis anytime! And thanks for the opportunity😊

**Pull request merged**
