### PR TITLE
feat: Added search bar hotkey tooltips

### PR DESCRIPTION
**Pull request by kuckertza**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

- Added search bar hotkey tooltips. 
- Added styling as discussed in related issue.
- Unable to test on a Mac os but working on windows 10.
### Related issue

- #79

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @kuckertza! Thanks for your interest in activist and for the PR 😊 I'm not seeing any tooltips within the [Netlify deploy preview for this PR](https://deploy-preview-101--activist-org.netlify.app/home/). Let me take a look into it a little later to check what's up, but could you confirm  that the behavior is not what you're seeing locally?

**Comment by andrewtavis** [comment]
I'll assign the issue to you :)

**Comment by kuckertza** [comment]
Happy to contribute! Sorry for the glitch. :( Both locally and on the Netlify deploy preview I'm seeing a tooltip when I hover over both hotkeys. Are you working on a mac os perchance? I'm on windows so I wasn't able to verify functionality but I looked into it further and I think the issue might be that device was not defined properly. It should be fixed now (if the problem was that you're on a mac). If not, happy to troubleshoot

**Comment by andrewtavis** [comment]
Hey again, @kuckertza :) I am on a Mac, yes. The problem still persists in the preview that I can't see the tooltips, and beyond that I'm now getting `^k` as the indicator for Mac rather than `⌘k`. I'm also a bit confused as to why the other recent commits are within this one. Looks like this PR needs to be rebased 😊 Would you be able to do that and then we can continue to try to figure out why the tooltips aren't working? I'd be happy to take a more in depth look at this if you'd like :) :)

**Review by andrewtavis — COMMENTED** [review]
Hey @kuckertza :) Sorry to jump into this and do it myself, but I was worried about some of the work that needs to be done to this PR including the refactoring to get all the other other commits out of this. I ended up using Tailwind for this. You can see my work for this in 6352fd3. Again very sorry, and I hope that you consider contributing again! I'm just trying to clear the issues that are here as I'm about to make lots more for the main web components 😊

**Pull request closed without merging**
