### PR TITLE
adding prod and dev requirements for the backend

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

In this PR, I seperated development requirements and production requirements for the backend with pip-tools. I adjusted the backend workflow/dockerfile to use the development requirements (`requirements-dev.txt`). 

General setup for this, min. requirements are in `requirements.in` and additional req. for the develpment are in `requirements-dev.in`. They are compiled to requirements.txt and requiements-dev.txt (including referenced packages). 

For example the djangorestframework is part of the requirements.in file and when compiled will reference necessary packages via comment in the requirements.txt file.
```
pytz==2023.3.post1
    # via djangorestframework
```

I have tested to run docker-compose up --build with both requirements. 

Before we consider merging this, we should update the readme and/or contrib. guide 😄. Mention how to use pip-tools, pip-compile and pip-sync.

### Related issue

- #450

### CODE REVIEW

**Comment by andrewtavis** [comment]
Let's discuss this in the dev sync, @to-sta, and then we can finalize the readme/contributing guide :) Feel free to send along an idea of what the changes to those should be though!

**Comment by to-sta** [comment]
@andrewtavis made a description here about the seperation of production and development. I am not sure where to place it in the contrib. guide. It's relevant when we need to switch between prod and dev and for installing new packages or testing.

In our backend development, we maintain a clean and efficient environment by separating production and development requirements. This is achieved using [pip-tools](https://github.com/jazzband/pip-tools), a set of command line tools designed to keep our pip-based packages fresh, even when we’ve pinned them.

We create two different requirement files: `requirements.in` for production and `requirements-dev.in` for development. The production requirements contain the packages that our project needs to run, while the development requirements include additional packages necessary for **testing, linting, and other backend development processes**.

To compile these `.in` files into `.txt` files that `pip` can understand, we use the `pip-compile` command from `pip-tools`. This creates `requirements.txt` and `requirements-dev.txt`, which are used to install packages in their respective environments. 

To transition between the production and development environments, you can simply use the following commands:

For the production environment:

`pip-sync requirements.txt`

For the development environment:

`pip-sync dev-requirements.txt`

Let me know what you think?

**Comment by andrewtavis** [comment]
Can you fix the merge conflict here @to-sta and I'll merge it in? :)

**Comment by to-sta** [comment]
Merge conflict is resolved and I also added django-cors-headers to the  requirements.in and requirements.txt file. That was still missing. The mypy step in the ci_backend check discovered the missing  package 😃

**Review by andrewtavis — APPROVED** [review]
Thanks so much for this, @to-sta! I keep on saying that the dev setup is getting so good and then it keeps getting better! 😊🚀

**Pull request merged**
