### PR TITLE
fix(ci): correct event type "pull_request"

### PR DESCRIPTION
**Pull request by wkyoshida**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

If I'm understanding correctly, I think the trigger event type that we would want is `pull_request` rather than `pull_request_target`. 

From the [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target):

> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the `pull_request` event does. 

### Related issue

- #489

### CODE REVIEW

**Comment by to-sta** [comment]
@wkyoshida when we switch to `pull_request`, we lose access to GitHub secrets.

We might have to adjust the workflow for this to work. I have to look into this.

**Comment by to-sta** [comment]
We can add environment variables to the workflow and then we can switch to use `pull_request`. 

```
env:
  SECRET_KEY = 'Add a secret key for the django backend here'
  DEBUG = True
  ....

```
Might make sense to place a comment in there "for testing purpose only".

**Comment by wkyoshida** [comment]
Right :thinking: 
@to-sta sorry, remind me again the cases of how we were thinking of using secrets in the workflows?

**Comment by to-sta** [comment]
> Right 🤔 @to-sta sorry, remind me again the cases of how we were thinking of using secrets in the workflows?

We are actually do not use any github variables or secrets in any of the workflows. I think the always had `pull_request_target` in workflows there? @andrewtavis.
I did not question that 😄.  

In order to run mypy we need the enviroment variables SECRET_KEY and DEBUG. But i just saw that we actually have a setup that defaults to DEBUG=False and generates a secret key inside settings.py everytime we run it. 

We can just switch to pull_request :).

**Review by to-sta — APPROVED** [review]

**Comment by to-sta** [comment]
After thinking about this for a bit, I would suggest to remove the default value for DEBUG and the SECRET actually, because this could cover up errors in our setup.

```python
DEBUG = int(os.environ.get("DEBUG", default=0))
SECRET_KEY = get_random_secret_key()
```

And since assign SECRET_KEY twice in settings.py we overwrite it. 

@wkyoshida what you think?

**Comment by wkyoshida** [comment]
Oh I see, gotchu! Just saw the `mypy.ini` file :+1: 

I'll be honest though - I haven't used `mypy` before, so I'm a bit unclear still how the env vars get used in the static type checks. Although, it does appear that the `mypy` step in the workflow is having issues working with env vars as seen in the [logs](https://github.com/activist-org/activist/actions/runs/6601379889/job/17932356293?pr=490#step:7:51). Noticed this same issue in most of the other open PRs and all of them erroring on an empty `DATABASE_NAME` env var (as seen in the log). Leads me to believe there might be a different issue as well going on with `mypy`.. :disappointed:  

Would it make sense for us to get this PR merged so we can at least get folks now running their CI on the correct commits? Then also open an issue to investigate why `mypy` is having issues with env vars? I can open it and assign to you (I assume that would make sense as you've been working with it so far, but let me know otherwise)

**Comment by to-sta** [comment]
I agree we should merge this PR. The issue with mypy is already adressed [here](https://github.com/activist-org/activist/pull/486#issuecomment-1774063105)

**Review by andrewtavis — APPROVED** [review]
Thank you both for the discussion here! 🙏 Glad to have this covered so we're not getting blindsided from now on :)

**Comment by wkyoshida** [comment]
And @to-sta glad you already figured out the mypy issue!! :muscle::rocket:

**Pull request merged**
