### PR TITLE
Fix: TS errors of ImageGithubShield and refactor GridGithubShields

### PR DESCRIPTION
**Pull request by luuu-xu**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

1. Fixes `ImageGithubShield`'s prop errors.
2. Refactors `GridGithubShields`'s `<script lang="ts">` to `<script setup lang="ts">`. Follows recommendations from Vue namely changing from [Options API](https://vuejs.org/api/options-state.html) to [Composition API](https://vuejs.org/api/composition-api-setup.html).

### Related issue

- #236

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks, @luuu-xu! Will get to this tonight or tomorrow :)

**Review by andrewtavis — APPROVED** [review]
Am caught in a rain storm and had the time to read through this all, @luuu-xu 🌧😊 Looks great based on the preview and the code’s very well formatted! Really appreciate it! Glad to have this in composition API now :)

**Comment by luuu-xu** [comment]
> Glad to have this in composition API now :)

Maybe we should also mention it in our documentation that it is preferred to use Composition API than Options API for our Vue frontend. And stick the API documentations next to them so it is easier for contributors.

**Comment by andrewtavis** [comment]
Also makes sense, @luuu-xu :) Wasn’t planning on being strict on this till we really started on TS, but we can now 😊 You’d be welcome to edit the docs, or I can do this this evening :)

**Comment by andrewtavis** [comment]
@luuu-xu, dfd01f9 includes some edits to the style guide including the direction to use the Composition API :) Thanks for the suggestion!

**Pull request merged**
