### PR TITLE
added directions on split dev environment

### PR DESCRIPTION
**Pull request by rstfari**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Add documentation on splitting front and back-end environments. ### Using Yarn or Python section added
to CONTRIBUTING.md at line 200. Link to this section added to README..md at line 192.

Made sure the link properly moves user to correct section.

### Related issue

- #617

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for this, @rstfari! @to-sta, do you want to send along some edits for how you'd want the backend to read? 😊

**Comment by to-sta** [comment]
This is a bit more complicated, since we can not run the backend without a postgres database. We use a postgres specific field (`ArrayField`) in our models what prevents us from using a `sqllite` DB. 

That means we still need to create a postgres DB.

Generally I think there are 2 ways of reducing the loading time:

1. Only run the database and the backend
    ```
    docker compose up --build db backend
    ``` 
2. Use Docker for the Database and then run the local server. 

    Here we need to adjust the .env DATABASE_HOST variable first. 
    ```
    # Current
    DATABASE_HOST=db
    # Changed
    DATABASE_HOST=localhost
    ```
    Then we can start the server:
    ```bash
    # In the root activist directory:
    cd backend
    python manage.py runserver
    ```

I can add the second option to the docs. What you think @andrewtavis?

**Comment by andrewtavis** [comment]
Is there any way to get it up without Docker, @to-sta? Remember that for Windows users even that might be too much 🤔 But then if memory serves me it seems to be finishing for the db and it's mostly the frontend that can't finish. If there's no way to get it without Docker then by all means send along the second method! We can always iterate as needed :)

**Comment by to-sta** [comment]
In order to run the backend without docker we need to make the backend models database agnostic with relationsships instead of postgres specific fields. 

This would mean, we have to change the schema, all models that use the ArrayField and create a local.py settings file that uses a sqllite DB instead of the postgres DB.

Would be a bigger issue to work on. 

I will add option 2 for now and we can discuss the changes necessary to accomplish that in a dev sync?

**Comment by to-sta** [comment]
Thinking about this again. We also need to make migrations and then migrate before we can run the server. I think this might be a bit too complicated. If we migrate we are also creating migration files that should be excluded inside the `.gitignore` file.

```bash
# In the root activist directory:
cd backend
python manage.py makemigrations
python manage.py migrate
python manage.py runserver
```

**Comment by andrewtavis** [comment]
Option 2 sounds like the correct route to me then :) Thanks for the further explanation, @to-sta! Good to have it documented in here as well. Let's do option 2 and we can react to it if it's still problematic!

**Review by to-sta — APPROVED** [review]

**Review by andrewtavis — APPROVED** [review]
All looks great to me 😊 Thanks for keeping at this, @rstfari! And thanks @to-sta for finalizing the backend directions :)

**Pull request merged**
