### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by amilliiee**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

FormKit validation PR to determine if we need to pivot.

### Related issue

- #841

### CODE REVIEW

**Comment by to-sta** [comment]
@andrewtavis, can you look into the styling of the error messages. 

In case you want to change or add error message, these are part of the schema now. 

```js
export const organizationSchema = z.object({
    name: z.string().min(1, "Name must have at least 1 character").max(55, "Name must be less than 55 characters"),
    location: z.string().min(1).max(100),
    description: z.string().min(1).max(1000),
    tagline: z.string().max(100).optional(),
    social_accounts: z.array(z.string()).optional(),
    topics: z.array(z.string()).min(1).optional(),
  });
```

You can insert a custom error message for every constraint (e.g. `name`).

**Comment by andrewtavis** [comment]
Is looking good, @to-sta! One thing for now is maybe we don't need to do a min topic as that won't be in the MVP?

**Comment by to-sta** [comment]
> Is looking good, @to-sta! One thing for now is maybe we don't need to do a min topic as that won't be in the MVP?

Hmm gotcha, but this field is optional but if it is provided it has to have at least one element. Thought that does the job for the current MVP and beyond 😄

**Comment by andrewtavis** [comment]
Makes sense 👍 Thanks for the explanation 🙏

**Comment by andrewtavis** [comment]
Quick note on this via a conversation with @to-sta: We do want to make sure that the errors are apparent to the user - specifically being formatted differently and being red text. This is something that should be achievable via adding in a custom `<style>` block, or could be done in the FormKit config file (the latter is likely best practice, if possible). If it's not possible to do this in the config, then we could certainly write a custom CSS file that can just be imported into the `<style>` blocks :)

**Comment by andrewtavis** [comment]
Thanks for your patience here, @amilliiee! Just now have gotten through the rest of the pressing PRs, and this one will be next :) It'll likely be sometime over the weekend before it comes in, but I'll get to it when I can 😊

**Review by andrewtavis — APPROVED** [review]
I'm assuming that the frontend error is related to the reset of the yarn.lock file, as prettier has been ran on the file. Really sorry about this review, @amilliiee... Have had a lot on my plate recently, and this + a decision to look into VeeValidate as something that styling should come a bit more easily to had this on the back burner for some time. Bringing in the changes with the FormKit work reverted, and I'll look into finalizing with the new process this week. The forms themselves need a lot of work, so I'll look to get as much of them switched over to Headless UI and other frameworks such that we can have as much accessibility and functionality coming from third parties as possible :)

Thank you! 😊

**Pull request merged**
