### PR TITLE
Feat: FAQ api

### PR DESCRIPTION
**Pull request by UnknownSean8**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

FAQ API in the backend based on the API schema.

### Related issue

- #661

### CODE REVIEW

**Comment by UnknownSean8** [comment]
This commit #689 is not the full functionality and have not merge with main. Thanks.

**Comment by to-sta** [comment]
@UnknownSean8 I added the rest of the fields and fixed a minor thing in the serializer.  You made the fields a python set instead of a list or tuple. That was causing a issue with the API.

**Review by to-sta — APPROVED** [review]

**Review by andrewtavis — APPROVED** [review]
Thanks for the work here, @UnknownSean8 😊 @to-sta and I sent along some minor fixes, and it's up and running now :)

**Comment by UnknownSean8** [comment]
> @UnknownSean8 I added the rest of the fields and fixed a minor thing in the serializer. You made the fields a python set instead of a list or tuple. That was causing a issue with the API.

Ahhhh, that's why, I was debugging for a long time and couldn't find it. I didn't do much here tbh hahaha, thank you @to-sta and @andrewtavis for the help!

**Pull request merged**
