### PR TITLE
#608. Create 'onTab' Function for Tooltip Visibility Control

### PR DESCRIPTION
**Pull request by ahmedy00**
- Added 'onTab' function in MenuSearchResult.vue to close the tooltip when the Tab key is pressed on the last element.

### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #608

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @ahmedy00! Functionality wise this is almost perfect! 😊 One thing I'm considering is whether we can get the tab to also go to the next element? Two situations for this:

- If we're on the last element of the tooltip, pressing tab will close the tooltip and focus the next element (as of now the next three dot menu)
- If we're on the first element of the tooltip, pressing shift tab will close the tooltip and focus the previous element (the three dot menu that opened the tooltip)

What do you think? Let me know and I'll either get to the review now or after the changes! I can also work on this myself if you'd prefer to swap over to backend (see message I sent you on Matrix about a first issue idea to help you get oriented).

**Comment by andrewtavis** [comment]
🔥🔥🔥 Nice @ahmedy00! I'll get to the full review now :)

**Comment by ahmedy00** [comment]
@andrewtavis, I fixed issues that you mentioned and I will check the backend issues, thank you for advise.

**Comment by andrewtavis** [comment]
I'll make the issue for the backend soon, @ahmedy00 :)

**Review by andrewtavis — APPROVED** [review]
All looks great, @ahmedy00! Thanks so much for the quick changes here 😊 Really great that we're keeping at a11y. Things are coming along great!

**Pull request merged**
