### PR TITLE
condition_classes_applied

### PR DESCRIPTION
**Pull request by Vidhanvyrs**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #263

### CODE REVIEW

**Comment by Vidhanvyrs** [comment]
hey @andrewtavis Please give the feedback for the applied changes

**Comment by andrewtavis** [comment]
Thanks for the PR, @Vidhanvyrs! I'm seeing that for the landing page in the deployment preview we're still getting the `flex-col` version at the large breakpoint. Specifically the conditions that we want to set for `FooterFlex` and `FooterFlexCol` should be along the lines of:

```
<!-- Note: Content Sections Top for Mobile -->
<FooterFlexCol class="flex flex-col" :class="{'xl:hidden': hasSidebar, 'lg:hidden': !hasSidebar}" :links="links" />

<!-- Note: Content Sections Left and Right for Desktop (xl) -->
<FooterFlex class="hidden" :class="{'xl:flex': hasSidebar, 'lg:flex': !hasSidebar}"  :links="links" />
```

The sidebar being open shouldn't change anything because at the `lg` and `md` breakpoints we'll just cover the page content and put an overlay over it after we finish #269. We can look into changing this behavior later though :)

I'd say generally the way to go about this would be to check the layout being applied. If the layout is `sidebar` then we want `hasSidebar === true`. Happy to look into how best to check which layout is being applied in Nuxt! And please let me know if the above needs a bit more explaining :) :)

**Comment by Vidhanvyrs** [comment]
yeah @andrewtavis thankyou for correcting it🙇‍♂️ i have done the asked changes and i think it should work and about this 
" I'd say generally the way to go about this would be to check the layout being applied. If the layout is sidebar then we want hasSidebar === true "
I think i already added the ref to it so this probably will work 
and yes let the  Cover screen with overlay issue get done then I can look into  that 🙇‍♂️😄

**Review by andrewtavis — APPROVED** [review]
The footer is definitely working the way it's supposed to @Vidhanvyrs. One thing is that now the sidebar's gone on pages that need it, but I'll play around a bit and get it back post merge :)

Thank you for working on this! I'll ping you in the issue once it's all finished up :) :)

**Pull request merged**
