### PR TITLE
#108 Image Popup Feature

### PR DESCRIPTION
**Pull request by Zwnow**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Related issue

- #108

### CODE REVIEW

**Comment by andrewtavis** [comment]
Taking a look now! Thanks firstly for updating the changelog! We need to start versioning soon after some of these initial issues are done :)

**Comment by andrewtavis** [comment]
And playing around with it now in the [deploy preview](https://deploy-preview-111--activist-org.netlify.app/en/docs/get-active), first things first let me say well done! Really is great :) There are definitely some things to improve, so let me first document them here and then maybe you can let me know what else you'd like to work on. I'm also happy to merge and work on some of this myself, but wanted to check with you on what you'd be interested in. What I'm noticing:

- On hover the mouse pointer for the image should change to a hand
- Rather than `Close` it'd be better to just have an `X` in the top right
  - This matched our [designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?node-id=1986%3A1046&t=5X0SayiGp2ogHLmz-1) a bit better
- Along with the above it'd be better if it spanned the window and rather than a border had a slight alpha component
  - This would also allow us to make the image larger
- On clicking anywhere outside the image the popup should close :)

That's what's jumping out at me 🙃 I'm not putting it in a review as again I'm 100% ok with merging and will then just accept it all. If you'd like to work on anything of the above, then just let me know and I'll do the review to request the changes 😊

Great work, @Zwnow! Thanks for your efforts! 🙏

**Comment by Zwnow** [comment]
I see, so remove border and add slight transparency, I can manage that too. Thanks for clarifying!

**Comment by andrewtavis** [comment]
You're very welcome for clarifying! Looking forward to the changes :) I'll send along the review now 🙃

**Review by andrewtavis — CHANGES_REQUESTED** [review]
As discussed int he conversation for this PR, there are a few changes that @Zwnow has agreed to try to solve :) Thanks @Zwnow!

**Comment by Zwnow** [comment]
Updated as requested! Looks a lot better now. :-)

**Comment by andrewtavis** [comment]
Looking into it a bit :) Firstly, epic! Well done 👏 Do you think it makes sense that the mouse is always a hand so they know that clicking will close. I think that it's just good to have the x to close it as a backup so people don't get confused. And speaking of the `x`, can we put an icon in there? `bi:x-circle-fill` within an `<Icon>` is what I've been using in the designs, and for the color `light-highlight` or `dark-highlight`.

**Comment by Zwnow** [comment]
Totally makes sense! Did not really know where to get the correct X, will work on it tomorrow. Thanks for your patience! I am having a lot of fun working on this.

**Comment by andrewtavis** [comment]
Having a lot of fun working on this with you 😊 Looking forward to tomorrow and closing this up! 🚀

**Review by andrewtavis — APPROVED** [review]
Really is some wonderful work here, @Zwnow! Thanks so much for following through with all this :) I'll do some very minor edits to finalize all this, but from my end this was quite the successful first issue 😊 If you're a Matrix user, please join us in the [community spaces for activist](https://matrix.to/#/#activist_community:matrix.org)!

**Comment by Zwnow** [comment]
Thank you! Was a very cool experience and I'm glad I was able to help 😁

**Pull request merged**
