### PR TITLE
update Header visibility reactive to scrolling.

### PR DESCRIPTION
**Pull request by purupurupu**
## Description
I tried to fix Header visibility reactive to scrolling.
Please let me know if there is anything that needs to be corrected.

## Related issue
#29

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hey @purupurupu! Thanks for this, and please don't stress about the requested changes 😊 This is a really good start to closing this issue 👏

Big thing is that the behavior isn't exactly what we're looking for. I'll define it a bit better :)
- At the top of the page the header has full opacity (as it does in your case)
- The user scrolls down -> the header disappears completely (0.0 opacity)
- The user scrolls up -> the header appears, and if the page isn't at the top then we'd have an opacity of 0.5 or so for just the background of the header
    - The logo and buttons would have full opacity, just the background would be a bit transparent

We need to test what opacity we want the header background to be to get this working effectively later on, but I think 0.5 is good to start 😊

**Comment by andrewtavis** [comment]
I'll go ahead and assign the issue to you as you're working on this 😊

**Comment by purupurupu** [comment]
@andrewtavis 
Oops, my bad.
Now that I know what it is, I'll fix the code.

**Comment by andrewtavis** [comment]
@purupurupu, looking forward! 😊

**Comment by andrewtavis** [comment]
@purupurupu, this is looking really good :) Have been testing it out just now. Only one comment, for `(scrollY > prevScrollY.value)` we want the whole header to disappear including the buttons, rather than just the background (maybe could have been a bit more descriptive). 

- `(scrollY > prevScrollY.value)`: everything disappears including the buttons
- `else headerOpacity.value`: background is 0.5 and the buttons are visible as you have it 👏
- `scrollY == 0`: everything is fully visible as you have it 👏

I'll calibrate the opacity and the transition time a bit once I merge 😊

**Review by andrewtavis — APPROVED** [review]
Actually let's leave it here 😊 I'm very happy with what's here now, and I want to use some Tailwind specific logic for the last parts of it 🤓

I'll update you in the issue on what I change!

**Pull request merged**
