### PR TITLE
Split apps

### PR DESCRIPTION
**Pull request by kurtisolo**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

**The backend has been divided into 4 apps:**
1. authentication
2. entities
3. content
4. events

**More details:**
- Some comments have been added at the top of each `models.py` file.
- For each app, the respective `views.py`, `urls.py`, etc. modules have been created.
- The code has been consequently distributed in the respective modules.
- The `settings.py` file has been updated accordingly.
- A 'templates' folder containing a `.keep` file has been added to each app.
- Some fields have been slightly modified to avoid import issues. For example:
Before: `verification_partner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)`  
After: `verification_partner = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, blank=True)`

### Related issue

- #322

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks, @kurtisolo! I’ll check the Netlify logs to see why we’re not getting a deploy preview here :)

**Comment by kurtisolo** [comment]
I just noticed i missed a line in `settings.py`

`"rest_framework",` should be added in the `INSTALLED_APPS` section.

Apart from this, let me know if there are any other fixes to be made!

**Comment by andrewtavis** [comment]
Including the missing `rest_framework` you also forgot to rename 'contents' to `content`, @kurtisolo 🙃 Looking at Netlify now :)

**Comment by andrewtavis** [comment]
@kurtisolo, what we're getting here is:

```
Failed during stage 'preparing repo': Error checking out submodules: fatal: 
No url found for submodule path 'backend/activist' in .gitmodules
```

For me on your branch and also when I bring it down locally `backend/activist` is an empty directory. On your branch it further has an arrow on the directory, which brought me to [this SO issue](https://stackoverflow.com/questions/62056294/github-folders-have-a-white-arrow-on-them). Do we need this directory, or can it be removed? Thoughts on this in general?

**Comment by kurtisolo** [comment]
I must have messed something up handling the repositories; I'm not even sure what exactly, lol. It can definitely be deleted.

As for 'content,' that's funny. I changed all the references in the various modules but forgot to rename the actual folder 😅.

**Comment by andrewtavis** [comment]
Feel free to send along the changes, @kurtisolo, and I'll finalize the review soon after 😊

**Review by andrewtavis — APPROVED** [review]
Will do a couple edits of spacing and rename some of the models your suggested before closing the issue, @kurtisolo, but overall looks great to me 😊 Appreciate your help here!

**Pull request merged**
