### PR TITLE
feat: create MenuMobileHeader component

### PR DESCRIPTION
**Pull request by dean123**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- Create MenuMobileHeader component
- Update SearchBarComponent to expand and collapse on click

### Related issue

- #196

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Sorry the review took so long, @dean123 :) Has been a really busy weekend with moving to a new flat. 

Thanks for this initial contribution! Requesting minor minor changes 😊 Firstly, would be good to remove the input focus highlights as for search bars it tends to not be implemented. The second ask is whether we could get the search bar when expanded to have a set distance to the meatball menu determining its width rather than having a fixed width.

I'm very happy to take a look at these myself if you're a bit busy :) I'll have some time tomorrow evening I think 😊 Thanks again so much!

**Comment by dean123** [comment]
Thank you @andrewtavis :) 

Yes maybe you can take it from here? I'm not sure if I'll find the time this week

**Comment by andrewtavis** [comment]
Sounds good, @dean123! Will merge later and finalize this :)

**Review by andrewtavis — APPROVED** [review]
Will approve this and merge based on our discussion, @dean123 :) Thanks again for this! Will send along the changes later today or tomorrow 😊

If you have time, would be great to have you on a dev call for activist tomorrow at 15:00 UTC (5pm Berlin). Details for that will be in the dev chat on Matrix soon!

**Pull request merged**
