### PR TITLE
schema update, factories adjusted and initial pytest to backend workf…

### PR DESCRIPTION
**Pull request by to-sta**
…low added

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Updated the schema to reflect the changes we made in the last dev sync. Tables are up-to-date with [schemas](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=5377%3A33014&mode=design&t=E1e23fOs8lygKJmO-1) in Figma. Factories are updated and an initial pytest workflow was added to the backend workflow.

I reverted the admin endpoint from the index page to `admin/` because it caused redirects to the admin login for the swagger url tests.

### Related issue

- #547

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks @to-sta! Do you have an idea of what's wrong with the failed backend tests?

**Comment by to-sta** [comment]
> Thanks @to-sta! Do you have an idea of what's wrong with the failed backend tests?

Yeah 😅, it's the pytest addition to the backend workflow. There is no database for the tests.

I will delete the addition of the tests and work on that separately. 

I just ran pytest local in docker and the tests all pass.

**Comment by andrewtavis** [comment]
Great, thank you @to-sta! Will get to this soon :)

**Review by andrewtavis — APPROVED** [review]
Thanks, @to-sta! All looking good based on the schemas. I did some reordering this morning, but let's not worry about that :) Let's now think about adding in the discussion models as that'll be needed sooner than tasks. I've checked with a contributor who wants to work on backend about it already 😊

**Pull request merged**
