### PR TITLE
All refactored except issue with hosted_by

### PR DESCRIPTION
**Pull request by akdave2003**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](CONTRIBUTING.md#testing)

---

### Related issue

 https://github.com/activist-org/activist/issues/968

- #968

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @akdave2003 👋 Thanks so much for sending this along :) I think the header problems are from the addition of `$t` properties in the HTML strings. Maybe we can convert those over to computed variables and then we can have them in the strings with `${computedVariableName}`? Happy to help with this!

**Comment by akdave2003** [comment]
I made this change is this what you are referring to? 
Screenshot 2024-12-08 at 8 52 40 PM

**Comment by andrewtavis** [comment]
That looks like a step in the right direction :) Do you want to send it along?

**Comment by akdave2003** [comment]
Changed and updated PR

**Pull request merged**
