### PR TITLE
Only one modal open

### PR DESCRIPTION
**Pull request by nicomaz**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

When opening a modal inside another modal, make the previous modal close so that only one modal is open at a time. When opening a modal for the first time, it creates an instance of that modal on the pinia store. Prior to this, it closes all modals already in the store, ensuring that only one modal is open at a time. 

### Related issue

- #845

### CODE REVIEW

**Comment by andrewtavis** [comment]
Nice @nicomaz! Thank you 😊 Will get to the review here in the coming days :)

**Comment by nicomaz** [comment]
Thank you @andrewtavis. :-) If there's any other issue that you'd like for me to look at, feel free to tag me!

**Comment by andrewtavis** [comment]
Lots of merge conflicts from the recent changes, @nicomaz, and there might be a few issues with how I got rid of them all. I'll do another scan of it all tomorrow and we'll figure this out/get it in 😊

**Comment by andrewtavis** [comment]
Nice ok, at least tests are passing :) I'll check that all's working tomorrow!

**Review by andrewtavis — APPROVED** [review]
All's working really really well, @nicomaz 😊 Thanks so much for this! Goes perfectly with how we're doing hydration as well :)

**Pull request merged**
