### PR TITLE
Update models

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

In this PR, I extend the models.py tables Resources, Users and Organization according to the [database schemas on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=5377%3A33014&mode=design&t=sAtZhV2c6WKZH0eV-1). 

And added updated the admin.py files. 

I ran docker and created a superuser to view the admin page. All models are registered.

image

There are a lot of models now 😄, might make sense to restructure this further before merge or down the line.

Another option i like in case we know there will be more frequent changes in the models for a while, is to use a for loop inside the admin.py to iterate over the models and register them one by one. 

```python
import django.apps

models = django.apps.apps.get_models()

for model in models:
    try:
         admin.site.register(model)
    except admin.sites.AlreadyRegistered:
         pass


```
### Related issue

- #383 
- #382

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks, @to-sta! I'll get to this tomorrow hopefully :) :)

**Comment by to-sta** [comment]
Had another look into this and I think we should remove `Groups` under AUTHENTICATION AND AUTHORIZATION. This comes by default with Django. We could unregister it, since we do not use it.

**Comment by andrewtavis** [comment]
Sounds good to me, @to-sta :) Feel free to send along another commit!

**Review by andrewtavis — APPROVED** [review]
Thanks for the changes here, @to-sta! Getting much closer to having a functioning backend with these 😊😊

**Pull request merged**
