### PR TITLE
#469 Password strength indicator

### PR DESCRIPTION
**Pull request by ahmedy00**
-zxcvbn package and types has been added
-Types configured in tsconfig.json file

### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #469

### CODE REVIEW

**Comment by andrewtavis** [comment]
Great to have you back, @ahmedy00! 🙌 I'll get to this soon 😊

**Comment by andrewtavis** [comment]
Do you want feedback on this, @ahmedy00, or should I work to finish up some things myself? Some things I'm thinking about:

- Let's have it be present even when the password hasn't been started yet as I don't like the jump for the rest of the content
- A bit of rounding of the corners would be good 😊
- Let's have some text under it as well as in the designs (right justified and `special-text` colored):
  - Password strength: invalid (bar color is `header` or `special-text`)
  - Password strength: very weak (bar color is  `action-red`)
  - Password strength: weak (bar color is  `cta-orange`)
  - Password strength: medium (bar color is  `pending-yellow`)
  - Password strength: strong (bar color is  `accepted-green`)
  - Password strength: very strong (bar color is  `text`)
- I think that having that last level where it goes to black for light mode or white for dark mode will be good 😎

Happy to work on these things myself if you're busy! Thanks for all this!

**Comment by andrewtavis** [comment]
Thanks, @ahmedy00! Really excited to see the final version! 😊

**Comment by andrewtavis** [comment]
Are we ready for a review here, @ahmedy00, or do you want to do a bit more? The workflow above failed because you haven't assigned the i18n keys as seen [here](https://github.com/activist-org/activist/actions/runs/7064013204/job/19231184442?pr=583), so maybe you're still planning on changing the text based on what the strength is?

**Comment by ahmedy00** [comment]
@andrewtavis I think this is related to the dynamic use of the` `components.password-strength.${text}`` line, what do you suggest to fix this situation

**Comment by andrewtavis** [comment]
Ah yes, I'm seeing it now. We can just do an explicit conditional where the keys are passed directly rather than using `${text}`? I know it's not the nicest way to code, but it is important that we maintain oversight over all the i18n strings.

**Review by andrewtavis — APPROVED** [review]
Really great, @ahmedy00 😊 I'll go through for a quick check as the colors are actually too transparent given the alphas. Let me have a look though and I'll send something along shortly!

**Pull request merged**
