### PR TITLE
config for coverage.py

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
I added configuration for the coverage report to exclude certain files and directories.

```toml
[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "tests.py",
    "asgi.py",
    "wsgi.py",
    "manage.py"
    ]
```

### Related issue

- #432

### CODE REVIEW

**Comment by andrewtavis** [comment]
@to-sta, was this linked to #515? Seems to have been merged when I merged that one 🤔 Let us know if you have any comments here, @wkyoshida!

**Comment by to-sta** [comment]
@andrewtavis my fault 🤯 , I built ruff formatter on top of this branch by accident. Then we need to add the coverage config back in. It's not part of the code base at the moment.

This should be added to the pyproject.toml file.

```toml
[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "tests.py",
    "asgi.py",
    "wsgi.py",
    "manage.py"
    ]
```
Can you add this to a commit  @andrewtavis  or should I do another PR?

**Comment by andrewtavis** [comment]
I'll send it along now, @to-sta!

**Comment by andrewtavis** [comment]
Done ✅😊

**Pull request merged**
