### PR TITLE
Specify frontend package dependency versions 

### PR DESCRIPTION
**Pull request by arescrimson**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This is for issue #872, where we are trying to specify frontend dependencies. This was done through just removing the carets and leaving a specific version number for each package. This has the effect of potentially resolving some issues where a released minor/major versions introduces new, unnecessary dependencies. 

**NOTE**: This is still a W.I.P - @andrewtavis I've left it as a W.I.P just in case you wanted to hop on the branch and look at the initial changes for yourself, see if this is on the right track, etc. 

**W.I.P List:** 

Resolving unmet peer dependency issues - I assume this is because some of the packages were using versions that don't match the ones that are now specified, so I'll resolve those. 

image
^ Looks like these warnings are mostly from one package, so hopefully straightforward fix. 

Testing to see if the application will still run the same previously with the new packages - this I'm open to suggestions/guidance for :) 

### Related issue

- #872

### CODE REVIEW

**Comment by arescrimson** [comment]
Looks like checks are failing because of **@nuxt/eslint-config**, which is the same one that's also producing those warnings. Honestly, from what I understand about **eslint**, I think we could maybe leave that one unspecified. Since it's just a linter, minor changes/releases hopefully just still be fine? 

Either way, I'll start looking for the proper version that fulfills that missing peer dependencies - maybe that's also what's causing the checks to fail as well.

**Comment by andrewtavis** [comment]
Thanks for this, @arescrimson! I'll be able to help here once a few more PRs are in. I'm finalizing the i18n ones tonight and then will start on others 😊

**Comment by andrewtavis** [comment]
Hey @arescrimson 👋 For the tests to see if things are working properly, for now sadly it's just "is stuff loading" as we don't have proper tests. I'll click around to make sure that things are progressing, and then we can make use of the browser tests we're building up eventually. Ultimately there's nothing to test against... Do you want to fix the dependency errors and merge conflicts and then we'll bring this in? Happy to help as needed!

**Comment by arescrimson** [comment]
Hey @andrewtavis just some notes on this - I had to leave **@nuxt-eslint** and **eslint** as loose dependencies since they were the ones generating the errors. This is also because I think if they were tied to one specific version, so many different packages rely on the different versions of **eslint** that they kind of have to be loose or we'll get a bunch of missing/incorrect peer deps. 

Let me know if it looks the same on your end, or if you want to change anything about this. So far, it looks like there are no warnings and that every package is working fine in their specified version, but just want to make sure 😄

**Comment by andrewtavis** [comment]
This is great, @arescrimson! I'll check it out tomorrow and bring it in before doing the Dependabot Nuxt update from the other PR. Appreciate you looking into this! Makes sense that we still need some loose dependencies, and hopefully those won't cause us to need to update dependencies when we're doing frontend linting tests. I think likely we won't 😊

**Comment by arescrimson** [comment]
Yep! I will say though @andrewtavis it was pretty straightforward to specify the versions, etc... but I think we all know how annoying the Node ecosystem can get sometimes when dealing with package dependencies, and I'm kind of thinking about how packages will interact going forward. For now, hopefully everything goes well, but in the future feel free to ping me if something starts breaking because that's something I'm a bit worried about 😅 

In addition, hopefully this also resolves issue #871 - unless any new packages are added for now, hopefully shouldn't have any unmet peer dependencies. I just tested it out with a fresh lockfile and it looks like there's still one error when fetching packages, but this should be how it looks for a person installing the project: 
image

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the efforts here, @arescrimson! Really great to have this figured out :) I'll play around a bit with the "trying to install in the same destination" error a bit so hopefully we can get a clean build 😊

**Pull request merged**
