### PR TITLE
Improve Route Handling for Localized and Non-Localized Routes

### PR DESCRIPTION
**Pull request by Mohtelsayed**
This pull request addresses issue #963 .

Description:

This pull request enhances route handling to accommodate both localized and non-localized routes. The core changes include:

Key Changes:

Locale-Agnostic Route Comparison: Introduced removeLocaleFromRouteName to strip locale prefixes from route names. This allows for consistent route comparisons, regardless of the current locale.
Subpage Detection: Updated isCurrentRoutePathSubpageOf to consider locale-stripped route names. This ensures accurate subpage identification, even when switching between locales.
Route Inclusion Check: Modified currentRoutePathIncludes to utilize locale-stripped route names, improving the reliability of route inclusion checks.

Benefits:
Consistent Route Handling: Ensures that route comparisons and subpage detection work correctly across different locales.
Simplified Logic: Streamlines route handling by removing unnecessary locale-specific checks.
Improved User Experience: Provides a seamless user experience, especially when switching between languages or navigating complex route structures.
Testing:

Tested the changes in various scenarios, including:
Navigating to subpages within different locales
Checking route inclusion and subpage detection under different language settings
Please review the code changes and provide feedback.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hi @Mohtelsayed 👋 FYI I'm seeing that your email isn't set up correctly for Git. Can you please check that the [email you use for GitHub](https://github.com/settings/emails) is the same as the response you get from `git config user.email`, and if not set it with `git config --global user.email "YOUR_GITHUB_EMAIL"`. Without this your account won't get the contribution :)

**Comment by andrewtavis** [comment]
Do you want to fix your email and then open another PR? You can also try to commit to this branch again :)

**Comment by Mohtelsayed** [comment]
@andrewtavis Should be set up now. Let me know if there is anything else.

**Comment by andrewtavis** [comment]
The commits here are still not for your account. Do you want to close this and open a new PR? :) Can also review this one, but as I said your account won't get the credit.

**Comment by Mohtelsayed** [comment]
Ok sure

**Comment by Mohtelsayed** [comment]
@andrewtavis How about now. I think it should be set up. If not ill just make a new one.

**Comment by andrewtavis** [comment]
I'll squash the commits and it should work now :) Thanks, @Mohtelsayed!

**Review by andrewtavis — APPROVED** [review]
Thanks for the contribution here, @Mohtelsayed! This definitely cleans up the route check functionality more and integrates well with the work from your classmates 😊

**Pull request merged**
