### PR TITLE
Added / hotkey in search bar

### PR DESCRIPTION
**Pull request by mud1tx**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

Added **" / "** hotkey to the search bar. By clicking the **" / "** button the search bar will be focused.

Also, please describe shortly how you tested that your change actually works --- By running the project on localhost:3000

### Related issue

- #64

### CODE REVIEW

**Comment by andrewtavis** [comment]
If you're a Matrix user, feel free to join us in the [public chat](https://matrix.to/#/#activist_community:matrix.org) so we can connect on future issues 😊

**Comment by mud1tx** [comment]
> If you're a Matrix user, feel free to join us in the [public chat](https://matrix.to/#/#activist_community:matrix.org) so we can connect on future issues 😊

Ahhh I have never used Matrix. What is this?

**Comment by andrewtavis** [comment]
Decentralized chat service :) It's kind of like Discord or other room based discussion platforms, but fully open source.

**Comment by mud1tx** [comment]
@andrewtavis Did you review it?

**Comment by andrewtavis** [comment]
I haven't had time, @mud1tx :) It does look all good and I'm expecting to merge it, but as of now I'm telling myself to finish something else and then switch to my PR reviews. Sorry for the wait!

**Comment by mud1tx** [comment]
@andrewtavis It's my first open source contribution that's why I am quite excited.No problem take your time.😃

**Comment by andrewtavis** [comment]
No stress, @mud1tx! I get the nerves 😊 Quite the contribution for your first one, btw!

**Review by andrewtavis — APPROVED** [review]
@mud1tx, really sorry this review took so long, especially with it being your first contribution! Appreciate the effort that you put in here and also the discussion we had to come to such a good solution 😊

Looking forward to future contributions! I'm very much switched back to activist as my focus going forward, so you'll not need to wait as long in the future :)

**Pull request merged**
