### PR TITLE
download-qrcode: new qrcode component and download

### PR DESCRIPTION
**Pull request by VinnyHS2**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request is for separate QRCode in a new component and add the logic necessary to make the button download work. To test it, just press the download buttom in the QRCodeModal.

### Related issue

- #472

### CODE REVIEW

**Comment by andrewtavis** [comment]
Nice @VinnyHS2! 🔥🔥🔥

**Comment by andrewtavis** [comment]
Looking forward to the review :)

**Review by andrewtavis — APPROVED** [review]
Formatting of the QR code's a bit weird and the icon's not showing up on at least dark mode, @VinnyHS2, but the I can finalize all this 😊 Pretty sure the icon issue's from before anyway and I didn't fix it properly. Really excited about this! :) Will write into the issue when it's all done ✅

**Comment by VinnyHS2** [comment]
Yeah, this problem with the dark mode was happening before, I even tried to solve it, but as you can see without success.

**Pull request merged**
