### PR TITLE
chore: implement cypress axe and axe core

### PR DESCRIPTION
**Pull request by lucianmurmurache**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #775

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @lucianmurmurache 👋 I updated the frontend dependencies - hence the merge conflicts. Let me know if there's anything I can do to help here!

**Comment by lucianmurmurache** [comment]
@andrewtavis apologies for the delay here, I did not have time to work on this further. I will try my best to pick it up again over the weekend. If anyone else would like to take over this task, I would be happy to also do a quick handover.

**Comment by andrewtavis** [comment]
No stress, @lucianmurmurache! Let's take a look this weekend :) Would be good to get it done, and then you and I can chat quickly about how the testing issues should look.

**Comment by wkyoshida** [comment]
:slot_machine:

**Comment by andrewtavis** [comment]
Merge conflicts are fixed here, @aasimsyed :)

**Review by andrewtavis — APPROVED** [review]
Brining this in as in conversations with @aasimsyed the decision was to switch to Playwright based on interest and what it can offer :) I'll close the associated issue and make a new one 😊 Thanks, @lucianmurmurache!

**Pull request merged**
