### PR TITLE
refactor(card topic selection): to use headless ui tab component

### PR DESCRIPTION
**Pull request by TeddyGavi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
[Screencast from 2023-11-29 05:02:57 PM.webm](https://github.com/activist-org/activist/assets/102203363/70b7f964-a5f9-4c6d-aa73-4381671fa9cb)

- refactor `CardTopicSelection` to use Headless UI `Tab` over `ComboBox` 
- `Tab` supports the use of the left and right arrow keys to traverse the tabs
- I worked to use a listener to override the default functionality of `ComboBox` 
- default operation as seen here https://github.com/tailwindlabs/headlessui/blob/6598db59b7c2d78d00bab4c9c9314a526ddb79e6/packages/%40headlessui-react/src/components/combobox/combobox.tsx#L656-L683
image
- However, I could not get the event to stop before hitting these cases
- Manually tested by creating a new organization on a locally running instance of the app

### Related issue

- #527

### CODE REVIEW

**Comment by andrewtavis** [comment]
Just checking some expected behavior here, @TeddyGavi:

- It seems like `selectedTab` might need to be reset to the first index when we tab away from the tab group?
- We start on [the preview's create page](https://deploy-preview-589--activist-org.netlify.app/en/organizations/create/)
  - Tab down and we get to `Justice`
  - Tabbing again goes to the checkbox (expected)
  - Tab back to `Justice` and then right right to `Environment` and select it
  - Tab to the checkbox and back and then we're back to `Environment`
    - I'd expect to tab into the first thing always, but maybe I'm off base on this
  - Also once we're back on `Environment` and we switch to `Justice` with the arrow keys, if we tab then we go back to `Environment` where I'd expect it to go to the checkbox
  - Also if we deselect `Justice` then we lose focus on it, then tabbing to it gets to it

Let me know how the above sounds to you, and please provide your feedback on the thought process! Thanks for all the work till now as well 😊

**Comment by TeddyGavi** [comment]
@andrewtavis I removed the `selectedTab` and set the default index to 0, with a sort() applied. 

Test this out and see if the tab and shift + tab works as expected :)

**Comment by andrewtavis** [comment]
Seems to be doing a bit better, @TeddyGavi. Issue is that it's the first option on load, and if that option is deselected then we jump to where it is when we tab into the tabs rather than the first position 🤔 Beyond that I'm still getting cases where we can loose the focus and the user will be forced to tab out and tab back in to do anything else. Example for this is tabbing into the tabs, arrow keys to `Environment` and select it, arrow keys to `Education` and select it, and then arrow keys to `Activism` and select it -> `Activism` is deselected, but we've also lost the focus state.

I can take a bit more of a look at it later. Time to sleep 😴 Thanks for the dedication here!

**Comment by andrewtavis** [comment]
Hey @TeddyGavi 👋 Let me know what your thoughts on this are :) Also happy to work to finalize it myself if you're a bit busy! I think it's right there and just needs some tweaking.

**Comment by TeddyGavi** [comment]
Hey @andrewtavis I'm happy to have you finalize it!

**Review by andrewtavis — APPROVED** [review]
Bringing this in and will work to finalize this, @TeddyGavi! Thanks for the hard work to bring this to fruition! 🙏

**Pull request merged**
