### PR TITLE
feat: add ability to open QR code in new tab on click.

### PR DESCRIPTION
**Pull request by Robot8lover**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Introduce basic functionality for opening a the QR code in a new tab as request in #645. Opens a new window containing an HTMLImageElement with the QR code as a png data url src. Tested on Chrome and Safari, and it works as expected though pop-up windows must be allowed.

### Related issue

- #645

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for this, @Robot8lover! Will get to it by early next week at the latest :)

**Comment by andrewtavis** [comment]
Something that I'm realizing here @Robot8lover is that no matter what ID we're on we're returning `1` for the ID for the QR code... This is the case for organizations, groups and events. Would you have interest in looking into this?

The only other comment is on the way the the `Open image in a new tab` label flickers when we hover over it itself. Could we figure out a fix for this? Specifically the cursor tends to be over it when the QR code modal is opened, so then the first thing the user experiences is the label flickering.

Really appreciate all the work here!

**Comment by andrewtavis** [comment]
Also, let me know if you can see the errors in [the workflows](https://github.com/activist-org/activist/actions/runs/9201644423/job/25371910903?pr=887). Would be happy to assist with those as well! I'll be away for the weekend, but will be happy to assist and bring this in next week!

**Comment by Robot8lover** [comment]
@andrewtavis I will take a look at that. And yes, I can see the errors, and I'll try to fix those.

**Comment by andrewtavis** [comment]
Thanks @Robot8lover :) Let me know if there's anything I can do to help!

**Comment by Robot8lover** [comment]
@andrewtavis I'm a bit confused what you mean when you say that no matter what ID we're on we're returning 1 for the ID. Where does this ID show up?

**Comment by Robot8lover** [comment]
Oh, I think I know what you mean – the QR codes point to /en/events/1 (or organizations/1 or whatever it is) instead of what they actually are from. This is based on linkURL, which is based on useLinkURL from [frontend/composables/useLinkURL.ts](frontend/composables/useLinkURL.ts), which bases itself off of the props object. Within [frontend/pages/organizations/[id]/about.vue](frontend/pages/organizations/[id]/about.vue) and the other organizations/[id] pages is the line `const organization = testTechOrg` so I believe that that's what is setting the id to 1. This would no doubt change in production though I'm not quite sure how it works yet and what creating an organization/event would actually do.

**Comment by andrewtavis** [comment]
Fantastic and totally makes sense, @Robot8lover! Was worried we had something hard coded, but if it's based on the ID of the object then we're good :) Thanks for the investigation!

Will get to the full review in the coming days 😊

**Review by andrewtavis — APPROVED** [review]
Thanks so much for this, @Robot8lover! Sorry that the review took as long as it did. Has been a very busy last couple of weeks, and I wanted to clear some other things so that I can focus more exclusively on activist 😊 Appreciate the discussions in the PR and the extra commits to get this all right! Will try to get the others in soon as well, and hope to be able to work with you more!

**Pull request merged**
