### PR TITLE
Add discussion and discussion_entry models to backend

### PR DESCRIPTION
**Pull request by anthonyshibitov**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

movement_id and vote_id are currently not implemented, denoted by comments.

Let me know if there's any issues with this. This is my first foray into backend stuff 🤠

### Related issue

- #619

### CODE REVIEW

**Comment by andrewtavis** [comment]
For now we'll just comment them out, @anthonyshibitov :) Thanks!

**Comment by andrewtavis** [comment]
Ok, soooo, this is quite weird. @to-sta, the errors that are coming up now for the backend are what I was seeing in PyLint that we said were false positives 🤔 Can you take a look?

**Comment by to-sta** [comment]
> Ok, soooo, this is quite weird. @to-sta, the errors that are coming up now for the backend are what I was seeing in PyLint that we said were false positives 🤔 Can you take a look?

Hi @andrewtavis, maybe its related but the backend workflow discovered static type issues and unsorted imports. Does pylint cover those?

I saw that inheritance was missing for the viewsets, that solves most of the static type issues. 
```python
class DiscussionViewSet:
     ...

class DiscussionViewSet(viewsets.ModelViewSet[Discussion]):
    ....
```

I think the rest of the static type issues are related to the use of model fields that don't exist.

**Comment by to-sta** [comment]
I fixed the mypy, linting and formatting issues. @andrewtavis and I renamed the `user_id` field from DicussionEntry to `created_by`.

**Review by andrewtavis — APPROVED** [review]
Final commit on my end was mostly keeping the changes from the branch here and organizing things. Thanks so much for this, @anthonyshibitov! Always a pleasure, and again apologies that this took so long. Also thanks for the fixes, @to-sta! 😊

**Pull request merged**
