### PR TITLE
`Header`: Refactor to use Composition API

### PR DESCRIPTION
**Pull request by RyanPaulGannon**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

I have changed `WebsiteHeader.vue` from the Options API to Composition API. I have also removed two types from `handleScroll` as TypeScript will infer these. 

I tested on localhost:3000 using `docker-compose-up`.

### Related issue

- #237 .5

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @RyanPaulGannon! Will definitely help with the work that's being done in #211 😊 Let us know if you have any interest in helping with all that. We'll be making individual issues to handle that soon :)

**Comment by RyanPaulGannon** [comment]
Cool, sounds good. I would be more than happy to help! 😄

**Comment by andrewtavis** [comment]
Sounds wonderful, @RyanPaulGannon! Keep in mind that we also have our bi-weekly developer sync call this Saturday that you’d be welcome to join. That’ll be at 15:00 UTC :) No stress if you already have plans though 😊 Exact details will be posted in the Development channel on Matrix later in the week 🧑‍💻

**Comment by RyanPaulGannon** [comment]
Okay cool, I should be good for this. I shall keep and eye on the channel! 🤓

**Pull request merged**
