### PR TITLE
Create topic dropdown component

### PR DESCRIPTION
**Pull request by iagocarmona**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Creating component dropdown topics

Closed dropdown
image

Opened dropdown
image

Hovered item
image

### Possible props
```javascript
  defineProps<{
    topic: string;
    hasIcon?: boolean;
    iconName?: string;
    isRounded?: boolean;
    items: string[];
  }>();
```

### Related issue

- #455 

I was thinking about adding a new property to talk about whether the dropdown will override the others, but I would like your opinion first.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @iagocarmona 👋 Looking really good so far! I wanted to check in with you on some options for this, and am glad you sent along some questions/suggestions 😊 What do you think about adding in typing functionality to the select functionality via [Headless UI's combobox](https://headlessui.com/vue/combobox)?

> I was thinking about adding a new property to talk about whether the dropdown will override the others, but I would like your opinion first.

Do you mean that the selected one would be the label? We could do that with the combobox, or what I was thinking was also to allow the user to select more than one? [This section of the docs](https://headlessui.com/vue/combobox#selecting-multiple-values) shows how we can select more than one. We'd then maintain the label of the component as is.

Let me know how this sounds! I think this would definitely make it easier for the user to quick select things, and filtering by more than one would make searches much easier.

**Comment by andrewtavis** [comment]
And what do you think of converting the [super long topic selection with all the checkboxes](http://localhost:3000/en/events) (see sidebar) to something similar to what we're talking above? We could have all the topics in a combobox in the sidebar, and for the component we're working on here it would just be those that the user has indicated as being their favorites in their profile so it's easier for them to select those :)

**Comment by andrewtavis** [comment]
Hey @iagocarmona 👋 How are you doing on this issue here? Do you think that a conversion over to [Headless UI's combobox](https://headlessui.com/vue/combobox) is possible? We're trying to use Headless as much as possible to make sure that we have accessibility at a high standard.

**Comment by iagocarmona** [comment]
Hello, Im working on this, I will change to use the this UI. I think it would be better too.

**Comment by andrewtavis** [comment]
Thanks @iagocarmona! Looking forward :) I can figure out the merge conflict when you resend as well - no stress. I flattened the i18n JSON so we can search for where we define the key and for all its instances during one all codebase search. Figured it'd be easier to make changes as we can also find and replace now 😊

Hope you're well!

**Comment by andrewtavis** [comment]
Hey there, @iagocarmona! Let me know what the plans here are :) I'll deal with the merge conflicts by dropping in the current i18n file before merge, so no stress. We can also check in on this on Saturday during the sync/Code Night if that could work on your end 😊

**Review by andrewtavis — APPROVED** [review]
Hey @iagocarmona 👋 There are a couple things that are relying on this at this point, so I'm going to bring this in and do a refactor for it being a combobox. Thanks for the contribution here! Sorry that the issue wasn't was well defined from the get go :)

**Pull request merged**
