### PR TITLE
Added the base documentation tab, and added the related links to the help and documentation pages.

### PR DESCRIPTION
**Pull request by jpw3667**
### Contributor checklist

- [ ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description
I added a baseline for the documentation tab and added the respective links to the help and documentation pages. Both of the help and docs pages have a header and all the links with descriptions next to them. The documentation tab is a start for the bigger one I would like to make.

### Related issue

- #85 
- #33 
- #35

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @jpw3667 👋 Looks like you also did a random edit to `backend/manage.py` as well 🤔 If you want to keep committing to this PR you’re welcome to. I’d again suggest that for this one we just do edits to the links within [SidebarFooter.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarFooter.vue), merge that, and then we can move on to something more complex :)

**Review by andrewtavis — CHANGES_REQUESTED** [review]
@jpw3667, big thing that needs to happen here is that these commits need to be [rebased](https://git-scm.com/docs/git-rebase). I have a responsibility to bring in clean commits to the code base. I understand that you had issues setting up the dev environment locally, but then using a deployment preview server as a means of testing your code is really not good practice. 

I assume that for your school project we can't just start a new PR, so basically what I'd need is for you to look into how to rebase commits and send everything that you have here as a single commit to this PR. I can help with this a bit if it's overly confusing, but I really would ask that you read the documentation and maybe watch a [YouTube video or two on the topic](https://www.youtube.com/results?search_query=git+rebase). My intention is to merge so that you get credit. I hope that editing the commit history is something that would be allowed within the project's scope for you to still get an ok grade. From my side I don't think I'd be willing to merge if for the project your code till now needs to stand as is.

**Comment by jpw3667** [comment]
I understand. I already submitted the project so we don't need to worry about that anymore. I still have one more final I'd like to focus on for the next few days, but after that I'll be sure to look into rebasing for this commit. I was also planning on improving that documentation tab I made to be more inline with what we discussed.

**Comment by andrewtavis** [comment]
All sounds good, @jpw3667! Good luck with your final and let’s check in on the rebase and some other changes when you’re done with that :) :)

**Comment by andrewtavis** [comment]
@jpw3667, let me know if you have time for the rebase soon :) Would be great to get this done as we actually need to start working on the sidebar component on Wednesday.

**Comment by andrewtavis** [comment]
Am going to close this PR, @jpw3667. You're more than welcome to send along the changes that you made to [frontend/pages/help/index.vue](https://github.com/activist-org/activist/pull/115/files#diff-64c0d865104370cdab565edf963dc356ebd327fa261e4037fead8bcfd4835693) and [frontend/pages/docs/index.vue](https://github.com/activist-org/activist/pull/115/files#diff-3007d4dd642483241092e38550b8ffebb0b281219c88672af20cf162bf76228c) as those can still be merged, but I think that it's best if we close this and start from scratch at this point. Hope you're well!

**Pull request closed without merging**
