### PR TITLE
Galib fixed copyright text as requested by issues/728

### PR DESCRIPTION
**Pull request by progressive-galib**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](CONTRIBUTING.md#testing)

---

#### Add Public Copyright License and Fix German Translation Issue in Footer 

This pull request addresses issue #728 by implementing the following changes:

##### Key Updates: 
1. **Updated Footer Copyright Notice**:  
   - Replaced the default "All Rights Reserved" copyright footer with a public license notice in alignment with the repository's AGPL license.  
   - The updated copyright now reflects "Copyright © 2023 activist, licensed under AGPL and CC BY-SA 4.0," ensuring compliance with the intended open licensing approach.   

2. **Translations Added**:  
   - Added appropriate translations for the updated copyright notice in the following languages:  
     - German (`frontend/i18n/de.json`)  
     - English (`frontend/i18n/en-US.json`)  
     - Spanish (`frontend/i18n/es.json`)  
     - French (`frontend/i18n/fr.json`)  

3. **German Translation Prop Name Fix**:  
   - Corrected a mismatch in the German translation for the prop {Jahr} by changing to {year}.

#### Files Modified:
- **Footer Component**:  
  - `frontend/components/footer/flex/FooterFlex.vue` updated to display the new copyright notice.  
- **Translation Files**:  
  - `frontend/i18n/de.json`  
  - `frontend/i18n/en-US.json`  
  - `frontend/i18n/es.json`  
  - `frontend/i18n/fr.json`  

###Testing
I did not test it as i committed while on an android tablet, but i am confident it will work.

### Related issue

- #[728](https://github.com/activist-org/activist/issues/728)

### CODE REVIEW

**Comment by andrewtavis** [comment]
Something that we could do for now @progressive-galib is to remove the copyright entirely as there's no legal entity and replace it with `AGPL-3.0; CC BY-SA 4.0`. That way we can just get rid of the i18n changes and the Nuxt config changes as well? What are your thoughts?

**Comment by progressive-galib** [comment]
along with https://github.com/activist-org/activist/pull/1056, i did to test Português and Español translations in the ui but figured its ready enough for production.

**Comment by progressive-galib** [comment]
https://github.com/activist-org/activist/pull/1054#issuecomment-2533271543

done and its actually working, you can merge 

and sorry for this [1056]https://github.com/activist-org/activist/pull/1056 adding  Português and Español, was a mistake.
i closed that PR

**Comment by progressive-galib** [comment]
merge please

**Review by andrewtavis — APPROVED** [review]
I switched over the license lines to just be AGPL and CC for now, @progressive-galib :) Will give the reason in the issue so the person who opened it can get an update on the result 😊 Really appreciate you taking this on and improving how we present ourselves!

**Comment by andrewtavis** [comment]
Failing frontend test is an unrelated known issue, so merging :)

**Pull request merged**
