### PR TITLE
Standardize i18n keys

### PR DESCRIPTION
**Pull request by jennethydyrova**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

1. Standardized all i18n keys by converting them to snake_case.
2. Updated STYLEGUIDE.md to reflect the new standard for naming keys using snake_case.

I manually verified the renaming of all keys by searching the codebase for the old key versions, and confirmed that none were found.

I apologize in advance for a big PR 🙂 

### Related issue

- #902

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks so much for this, @jennethydyrova! I'll try to get to the review soon :)

**Comment by andrewtavis** [comment]
Hey @jennethydyrova 👋 Quick note that I'm going to wait on #946 to close this out as if I merge this in first the conflicts are gonna be pretty crazy 😊 Do have it in mind though!

**Review by andrewtavis — APPROVED** [review]
This was quite the effort, @jennethydyrova, and I really appreciate all that you did here! Lots of changes on my end as well :) To let you know what's happened:

- I made some new scripts after discussing with another contributor and those are checking the validity of our keys based on the file in which they're used
- I also wrote a minor check to make sure that there are no keys used in target files that aren't in the source file
- Based on those scripts I made the changes that just came through

Really great to have this done! Thanks so much 😊 Hope to work with you again :)

**Comment by jennethydyrova** [comment]
> This was quite the effort, @jennethydyrova, and I really appreciate all that you did here! Lots of changes on my end as well :) To let you know what's happened:
> 
> * I made some new scripts after discussing with another contributor and those are checking the validity of our keys based on the file in which they're used
> * I also wrote a minor check to make sure that there are no keys used in target files that aren't in the source file
> * Based on those scripts I made the changes that just came through
> 
> Really great to have this done! Thanks so much 😊 Hope to work with you again :)

Thank you, Andrew!

**Pull request merged**
