### PR TITLE
fix(matrix icon): add custom vue component with wider viewBox for better scaling

### PR DESCRIPTION
**Pull request by eloi-cht**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Fix the Matrix logo resolution scaling issue on md+ screen by making font size bigger and adjusting scaling, which also make logo bigger and scale better on large screen.

Tested on Linux with Firefox on my 1920x1080 laptop screen, using different zoom and Firefox mobile viewer.

### Related issue

- #205

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hey @eloi-cht! Thanks for your interest in the project and wanting to help out here :) While your solution does fix the issue of the icon not showing up well, I really would prefer to keep the text sizing as it is. Having the social banner icons span longer than the text and main header above them really doesn't sit well with me as I look at it. It just looks unbalanced.

Let's work on changing the icon :) I played around with it a bit right now and I think changing the icon we're using and making it a bit bigger will work for this:

```
<Icon name="simple-icons:matrix" size="1.15em" />
```

Do you want to try this out and send it along if you think it'd work?

**Comment by eloi-cht** [comment]
Hey @andrewtavis, thanks a lot for your answer ! I find activist concept really great and I'm happy if I can help and gain some skills aswell.
I looked a bit more into it and it seems to me that the nuxt-icon module have an issue with SVG getting cropped on the right at certain zoom. It happens aswell on [icone.js](https://icones.js.org/) and [Nuxt-icon Playground](https://stackblitz.com/edit/nuxt-icon-playground?file=app.vue), it is clear on Matrix logo and you can see it on others if you look closely (round one mostly).
It seems to not happen anymore when setting a bit larger viewBox on the SVG component, i'll try to look more into it.

**Comment by andrewtavis** [comment]
Happy to have you as a contributor and that you can gain some skills, @eloi-cht! 

And thanks for the research that you’ve done already on this! Looking forward to what else you find out and getting this closed :) Can you write in #205 so I can assign this to you?

**Review by andrewtavis — APPROVED** [review]
Looks great, @eloi-cht! Sorry, I thought I'd written back to you in #205 :) Thanks so much for all the research here and trying out solutions! Really appreciate the care you put into this. Especially with how important Matrix is for activist, I think that making sure we get this icon right is worth a component 😊 

Looking forward to working with you again!

**Pull request merged**
