### PR TITLE
organisation api completed

### PR DESCRIPTION
**Pull request by bharath637462**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #627

### CODE REVIEW

**Comment by andrewtavis** [comment]
@bharath637462 we need to you to follow directions on what the work you're supposed to be doing is. #627 is assigned to me. You wrote into the issue asking if you could work on it, and you were not given permission to work on it. Please do not do any other backend API work at this time, and please focus on completing the work for #611. Once that is done you can begin working on #628 or another API issue once we have assigned the issue to you.

@to-sta and I will review this, but understand that further PRs like this where you haven't been assigned will be closed.

**Comment by andrewtavis** [comment]
Do not send along further commits to this issue. We'll finalize it ourselves.

**Comment by to-sta** [comment]
@andrewtavis 

<ins>Workflows:</ins>
the pr_ci_backend check fail do to a simple linting issue and the mypy check fails because we are overwritting the ViewSet methods with a subclass of the Superclass. 

Here is an example:
```python
backend/entities/views.py:48: note:      Superclass:
backend/entities/views.py:48: note:          def create(self, request: Request, *args: Any, **kwargs: Any) -> Response
backend/entities/views.py:48: note:      Subclass:
backend/entities/views.py:48: note:          def create(self, request: Request) -> Response
```
Since we do not use *args and **kwargs we are overwritting the Superclass. I would say we ignore that issue and add a top level comment again with:

```python
# mypy: disable-error-code="override"
```
<ins>API:</ins>
Since we need to have an `Organization` instance before we can create a `organization_application`, I would suggest to add creating the `organization_application` within the OrganizationViewSet's create method or overriding the Organization model save method. 

The workflow for creating a Organization would be:

`https://activist.org/de/organizations/create/ `-> this would use the `OrganizationViewSet `create method (POST) to create an Organization if the user is authenticated. If it is successfully created, we would also create a organization_application instance with the default status. Here we need to have the organization_application_status before we can create an organization_application. We can create a fixture for this, that we load in with `docker-compose.yaml`.

Should we add a unqiue constrant to the name field of Organization model?

Other then that the create method looks fine to me!

**Comment by andrewtavis** [comment]
I'll check this out a bit later, @to-sta. Wanted to remove the frontend changes so we're fresh :) Thanks for the details you've sent along!

**Comment by to-sta** [comment]
@andrewtavis I added the models for status as discussed. I added `unique=True` to the org. name. I was testing the endpoints with swagger ui and saw that i am able to create duplicates. 

I made some changes to the serializer, now the `deletion_date` will be excluded from responses. We can get back to this when we work on the destroy method. created_by is set on the created method by the authenticated user, therefore the field should be a read_only field. `status_updated` and `acceptance_date` that should be set in the backend and therefore are also read_only. 

```python
class OrganizationSerializer(serializers.ModelSerializer[Organization]):
    class Meta:
        model = Organization
        exclude = ["deletion_date"]
        extra_kwargs = {
            "created_by": {"read_only": True},
            "social_accounts": {"required": False},
            "status_updated": {"read_only": True},
            "acceptance_date": {"read_only": True},
        }
```

**Comment by to-sta** [comment]
I additionally removed the logic from update, partial_update and destroy, since these methods still need to be properly implemented. Since these 3 methods only have pass instead of a return value the ci_backend workflow is failing.

**Comment by to-sta** [comment]
Thinking about the destroy method of the org API. We have a `deletion_date` field on the organization model. What logic should I implement here:

Keep the org after deletion (any fields that should be removed?), set a `deletion_date` (and `status_updated`) as well as assign a new `status`?

**Review by to-sta — APPROVED** [review]

**Comment by andrewtavis** [comment]
@to-sta, sorry for the broken backend run. I don't think that any of the changes that came through in this would be problematic, but maybe it's because there are parts of the code in here now that aren't accounted for in this PR as it's coming from other commits? Can you do a quick fix of the backend errors and I'll bring this in?

**Review by andrewtavis — APPROVED** [review]
Thank you for all the hard work here, @to-sta! (also for the quick fixes just now 😅) So happy to have this finalized 🚀

**Pull request merged**
