### PR TITLE
feat: grid filter tags with a11y

### PR DESCRIPTION
**Pull request by UnknownSean8**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Grid Tags that are similar to topics with a11y.

### Related issue

- #556

### CODE REVIEW

**Comment by UnknownSean8** [comment]
I'm having problems formatting using prettier due to the prettier tailwind plugin. 😦

**Review by andrewtavis — APPROVED** [review]
My commit adds in the needed formatting and makes some minor changes, @UnknownSean8 😊 Big thing was adding in selection on return for the switches :)

Thanks so much for this! Great that it's all looking so consistent now!

**Comment by UnknownSean8** [comment]
Thanks for helping to fix it! :)

I'll try to install pre-commit and see how it goes.

**Comment by andrewtavis** [comment]
pre-cmmit wouldn't have helped with this, sadly. As of now it's turned off for Prettier until we get some bugs with the Tailwind ordering figured out, but should be there soon :) Maybe check that you have the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension installed and set it to autoformat on save? It should follow our eslint rules such that things will be corrected as you go. I literally did nothing to fix the formatting except save the file when I brought it down. You know that it's all working when you can screw up the formatting and the Tailwind ordering and it'll get fixed on save ✨

**Pull request merged**
