### PR TITLE
Add event to CardsSearchResult.vue

### LINKED ISSUE #121: Events search result component
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create parts of the search result component that is being made in #119. We want the features made in this issue to be conditionally switched to based on the whether `event` is passed to the aforementioned component's props :)

The designs for this component can be found on the [Components tab in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1606%3A585&t=5CR5mIoy4P0OjwjS-1) and can further be seen below:

Mode=Light, Mobile=False, Type=Event, Reduced=False

Mobile:

Mode=Light, Mobile=True, Type=Event, Reduced=False

- This issue is blocked by #119 that makes the baseline component

### Contribution

Happy to provide to support to someone with interest in working on this, or will also get to it eventually 😊

### PR DESCRIPTION
**Pull request by anthonyshibitov**
Add conditional render on receiving an event prop to display a test event as defined in home.vue

### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

Add event search result. Made a small fix in the organization search result where a default image wasn't being displayed properly if it wasn't passed an imageURL.

I also added a conditional icon depending on whether the event is online or in person. The design docs didn't specify this, so let me know if you want this removed :)

I also removed `flex-col` from the parent div so I could get the child div to grow and allow the right-alignment for the location and date-time info. Is this going to break anything down the line, or is there a reason `flex-col` was originally added?

Screenshot 2023-05-29 at 7 41 06 PM

### Related issue

- Closes #121

### CODE REVIEW

**Comment by anthonyshibitov** [comment]
Ah, I see the original issue #121 includes a mobile design.

When I try to preview the current `/home` layout, it looks like the mobile design is breaking even for the default organization search result. Should the mobile design be included in this PR?

**Comment by andrewtavis** [comment]
Thanks, @anthonyshibitov! Will take a look in the coming days :) :)

**Comment by andrewtavis** [comment]
And ya the mobile design is weird right now. Didn’t put too much thought into it as we need the sidebar to not be there anyway. I’ll make another issue for it 😊

**Review by andrewtavis — APPROVED** [review]
Sorry for the delay on this, @anthonyshibitov! Am in the midst of moving right now :) All looks good! Let me know if you have interest in #122 😊

**Comment by anthonyshibitov** [comment]
> Sorry for the delay on this, @anthonyshibitov! Am in the midst of moving right now :) All looks good! Let me know if you have interest in #122 😊

 no worries, hope the move went smoothly!

**Comment by andrewtavis** [comment]
Is a work in progress 😅😅😊 But thanks!

**Pull request merged**
