### PR TITLE
#354 #346 composable state for menu/sidebar components.

### PR DESCRIPTION
**Pull request by Robert-Kovalcuk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #354
- #346

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @Robert-Kovalcuk 👋 Confusingly this isn't the spaces at the end of the file alone, but it's actually reverting the i18n changes as I'd feared. Not really sure what to do here 🤔 The version of the frontend you copied over has the old i18n keys, so because of that it's overwriting the new ones as you copied it into a fresh fork of the repo. Easiest would likely be to only copy the files that are for this issue over and then I can go through and fix the i18n keys in them if need be?

**Comment by andrewtavis** [comment]
The no such file or directory for i18n is also because your fork has the old version/name of that file :)

**Comment by Robert-Kovalcuk** [comment]
But I remember that I pulled the commit with the i18n while we were on a call. Hmm, let's figure it out tomorrow?

**Comment by andrewtavis** [comment]
Ya it's very confusing. I remember you did that too. But ya, we can check it all tomorrow 😊 Thanks and till then!

**Comment by andrewtavis** [comment]
Closing this due to new version in #539 :)

**Pull request closed without merging**
