### PR TITLE
Switch from container to local with env variable

### PR DESCRIPTION
**Pull request by cquinn540**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#testing)

---

### Description

I made a bit of a design decision here.  I wanted to make this user friendly, so now if you set the env variable `DJANGO_ENV=LOCAL_DEV` you can run the backend locally, but you can also spin up the full container deployment without having to edit the env files.

This worked seamlessly on my mac with django running locally talking to the postgres container.  Unfortunately I don't have machines with other OSs so I can't verify that it will work as seamlessly in other environments, but you should be able to further customize `.env.dev.local` if you need to as any variables in there will overwrite the ones set in `.env.dev`.

I tried running both the UI and the backend locally and the file watchers opened more files than my system can handle, but I confirmed that the UI container will work with both versions of the backend.

Let me know if you think this approach makes sense or if you want more detail in the docs!

### Related issue

- #747

### CODE REVIEW

**Comment by cquinn540** [comment]
Looking at the errors it looks like stricter type checking is flagging some unrelated files?

**Comment by andrewtavis** [comment]
Could be, @cquinn540. In that case I can take a look :)

**Comment by andrewtavis** [comment]
But if you have suggestions let me know 😊 Great to have this PR in!

**Comment by cquinn540** [comment]
Figured out most of the type errors.  One I think is best to ignore because I don't think there is any easy way to track down the needed generic type.

I'm not sure how to run the frontend tests locally

**Comment by andrewtavis** [comment]
You can check the [testing section of the contributing docs](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#testing), which should have everything you need. Let us know if it's a bit incomplete though!

**Review by andrewtavis — APPROVED** [review]
Really appreciate the consideration of the developer experience here, @cquinn540! Thanks so much 😊

**Pull request merged**
