### PR TITLE
feat: copy url and redirect to signal when share link is clicked

### PR DESCRIPTION
**Pull request by UnknownSean8**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This is the same PR from the other signal additional PR. I have a problem with my git so I had to recreate the branch.

For the implementation, I feel like there is still improvement that can be made, especially with the duplicated copy URL code. Feel free to let me know if there are any ideas/comments.

Also, just an idea, maybe we could add in a "Redirecting to Signal" infobox or something to let the user know that it is redirecting to signal.

### Related issue

- #694

### CODE REVIEW

**Comment by UnknownSean8** [comment]
@andrewtavis Hi, I've fixed the comments that you listed yesterday. Do let me know if there are any changes needed. Thanks!

**Comment by andrewtavis** [comment]
Hey @UnknownSean8! The idea of maybe a toast to that says that Signal is going to open is a good one 😊 Let's maybe not include it in here, but have a separate issue that implements this for all the share functionality that needs it? Would you want to work on that? I could make the issue :)

**Comment by UnknownSean8** [comment]
Sounds like a good idea! I would be happy to work on it. Thanks!

**Review by andrewtavis — APPROVED** [review]
Really really nice, @UnknownSean8! Let's maybe change the `Copied` to `URL copied`, but I'll do that in the keys :) Will make the issue for the toasts now!

**Pull request merged**
