### PR TITLE
Cronjob

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Cronjob workflow for the find repeat i18n values python script. I gave it a test run with act.

@andrewtavis 
The workflow does not fail. I think we could automatically create an issue with the result (I think that should be possible 😅) or have conditionals in the workflow. Let me know what you think would be useful, than we can add this functionally to the workflow.

The script is set to run at 6pm, every 14 days on a Monday.

- #530

### CODE REVIEW

**Comment by andrewtavis** [comment]
What about running this on PRs, @to-sta? Definitely opening an issue automatically would be cool!

**Comment by andrewtavis** [comment]
The thing is, say there's a big change to the codebase that we merge and then i18n needs to do some work right after. If we wait for 10+ days the repeats would be potentially annoying multiple people. Sorry if I didn't get this fully in the sync (long day 😅). Let me know what you think!

**Comment by to-sta** [comment]
> The thing is, say there's a big change to the codebase that we merge and then i18n needs to do some work right after. If we wait for 10+ days the repeats would be potentially annoying multiple people. Sorry if I didn't get this fully in the sync (long day 😅). Let me know what you think!

haha I thought its too much running this on every PR 😄.

I thought running this on every PR might be excessive 😄. I believe that if we run this on every PR, we might end up running this script too often without creating value.

What we could do instead is run this script only when certain files are changed. Here’s an example for .js files.

Here is an example on `.js` files.
```yaml
on:
  pull_request:
    paths:
      - '**.js'
```

We could target the [en-US.json](https://github.com/activist-org/activist/blob/main/frontend/i18n/en-US.json) file and run the script whenever it changes.

**Comment by andrewtavis** [comment]
This is exactly what we should do, @to-sta! 😊 The magic of coding 🌈✨😇 Do you want to send along the change for that and we can merge it in? I'll be editing the JSON tomorrow or the next day and we can then see that it passes when they're all unique.

**Comment by to-sta** [comment]
> This is exactly what we should do, @to-sta! 😊 The magic of coding 🌈✨😇 Do you want to send along the change for that and we can merge it in? I'll be editing the JSON tomorrow or the next day and we can then see that it passes when they're all unique.

Switched from a cronjob to targeting the file directly. I also added `push` besides `pull_request` to catch changes that you commit directly. 

I still want to improve this a bit. The workflow will not fail, because we are not raising an error inside the python file or have a condition in the workflow. So we have to check the workflow run to see what has changed. Automatically creating an issue would make sense here (but consecutive commits would create a lot of Issues 😆). 

Let's improve this in another Issue 😄.

**Review by andrewtavis — APPROVED** [review]
Really great, @to-sta! I'll try to send along the i18n updates soon so we can test this :)

**Pull request merged**
