### PR TITLE
Card resource search

### PR DESCRIPTION
**Pull request by anthonyshibitov**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Added a hard-coded resource test search result to home. Also updated
the resource typescript definition to include an optional imageURL
seeing as the other cards had that property.

Also make some small tweaks to the other cards on how the icons were
being displayed with secondary information (location, org, attendees,
date, etc) to make them align with the text. Originally, they were 
slightly offset downwards by a few pixels. 

### Related issue

- #122

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hey @anthonyshibitov! Thanks for this 😊 There are merge conflicts atm that I can't fix as in order to get the routes working for the organizations home and events home I needed to move the home page to `home/index.vue`. Could you fix the conflicts in another commit and then I can merge?

**Comment by andrewtavis** [comment]
With the commit could you also update the [CHANGELOG](https://github.com/activist-org/activist/blob/main/CHANGELOG.md), @anthonyshibitov? :) You can just change the line about search results in features for `0.1.0` to include resources?

**Comment by anthonyshibitov** [comment]
@andrewtavis alrighty, this was my first time merging branches and resolving conflicts. hopefully i didn't break anything lol

**Review by andrewtavis — APPROVED** [review]
Looks all good, @anthonyshibitov! Thanks for getting to this 😊 

We're getting really close to having the current set of issues finished, and then we can make some more that'll also relate a bit to the backend. Let me know if there's something you like to work on or if you'd like me to make an issue for a component for you 🙃 You could check the [components on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1606%3A585&t=ltqMHBWFqG8SkXaZ-1) and see if there's something that catches your eye :)

**Pull request merged**
