### PR TITLE
Create factories and tests for the entities

### PR DESCRIPTION
**Pull request by marcosquadross**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR create a new file with de entitites factory and add the tests. 

### Related issue

- #ISSUE_NUMBER
#508

### CODE REVIEW

**Comment by to-sta** [comment]
@marcosquadross thank you for the work you put into this 🚀 . I will check the PR in the next days. 

Btw, the backend workflow fails because of static type checking, but this is not an issue. `factory_boy` does not support stub files and therefore, I will add the files to be ignored in the mypy config.

**Comment by to-sta** [comment]
@andrewtavis since there are a lot of reference to other factories (subfactories), we need to wait till the rest of the factories are done, before we can properly test if it works. 

I would say we can merge this after the change request and than keep the issue open.

**Comment by andrewtavis** [comment]
Yes I'll merge later, @to-sta :)

**Comment by to-sta** [comment]
@marcosquadross I made some minor adjustments. Thanks for your work on this 😃

**Review by to-sta — APPROVED** [review]

**Review by andrewtavis — APPROVED** [review]
Thank you for the work here, @marcosquadross! Hope we can work with you again soon 😊 And thanks for the review, @to-sta!

**Pull request merged**
