### PR TITLE
Command Palette with Headless UI and minor UX improvements

### PR DESCRIPTION
**Pull request by mattburnett-repo**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR builds on the Command Palette functionality already merged with the main repo.
- Implements HeadlessUI components.
- Provides minor improvements to UX (clicking or pressing Enter key on selected items).
- Moves data for the component to a separate file (CommandPaletteData.js).
- Implements basic search functionality for Command Palette data items.

This version of the component serves as a good starting point for further development of the Command Palette functionality.

### Related issue

No known related and currently-open issue.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @mattburnett-repo 👋 There were a lot of changes in how modals work that came through in #881, and because of this we have some conflicts with the new changes :) Do you want to do a call to check these, or would you want to check them first?

**Comment by mattburnett-repo** [comment]
I sent you a message over Element about the conflicts. Probably best for us to do a vid conf to sort the conflicts out. Plus, I'd like to get up to speed on what the modal changes are.

**Comment by andrewtavis** [comment]
Sure thing, @mattburnett-repo! Looking forward :)

**Comment by andrewtavis** [comment]
Taking a look at this with @mattburnett-repo right now :) We've closed out the merge conflicts from #881, but as of now both methods of opening and closing the modal are included in the script tag. We should check specifically for if we need to emit the close anymore, which maybe we do need to as this could be specifically targeting `ModalBase` :)

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @mattburnett-repo! Really great to see this at such an advanced state. In the most recent commit I:
- Removed a rogue `package-lock.json` (not sure if you're using NPM for things, but let's avoid it if so)
- Moved the TS file to the types directory as as of now we have only components in the components directory and their corresponding TS files are in types
  - Also got rid of the `command-palette` directory 
- Did some minor renaming :)

Let's be in touch on next steps! I'm going to be pinging you in a bug shortly, actually 🐞😊

**Pull request merged**
