### PR TITLE
feat(landing page): Initial commit of github icon shields

### PR DESCRIPTION
**Pull request by rohram04**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

Created Github Icon shields as requested in issue #170 like so:
image

The shields are currently in a grid component and the leftmost visit us shield is actually an <a> tag linking to [https://github.com/activist-org/activist](https://github.com/activist-org/activist).

Please note that it is probably better to separate each of these icon shields into their own component files. Also I utilized vue.js options api as I was having trouble getting the composition and normal api to work.

### Related issue

- #170

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for your strong initial dedication to activist, @rohram04! 😊 Looking forward to getting these on the landing page :) :) Will review later today odds are.

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hey @rohram04, checking this one out first 😊 I agree with you on the following:

> Please note that it is probably better to separate each of these icon shields into their own component files.

Do you want to make three different icon files within the `Icon` directory and then a grid component within the `Grid` directory that houses them all? And as far as links are concerned, maybe we can do a link to the [forks of activist](https://github.com/activist-org/activist/forks) for the forks link and the [stars for activist](https://github.com/activist-org/activist/stargazers) for the stars one?

A final note would further be could we get `Visit us on` a little bit over to the right? I know that it's inline, but given the curvature of the letters it looks like it's to the left a bit :)

Thanks so much for the efforts here! I'll jump over to #179 right now :)

**Comment by rohram04** [comment]
Hello, I made some changes to the files. Because the components are so similar I decided to make an IconGithubShield component and then use the <slot> tag to pass in child components (svgs and other divs), instead of creating 3 separate components. This reduces repetition. Let me know if this approach works for you.

**Review by andrewtavis — APPROVED** [review]
Thanks for the quick edits to the components, @rohram04! Will play around with these a bit and then add the section in to the landing page 😊 Will write in the issue when it's been added :)

**Pull request merged**
