### PR TITLE
.env.dev changed to .env

### PR DESCRIPTION
**Pull request by bharath637462**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by bharath637462** [comment]
hi i have changed .env.dev to .env i run localhost:3000 frontend sucessfull ran. Before changeing i have facing 
thinq24-kalai@thinq24-Latitude-5400:~/Downloads/activist-bharath$ docker compose up
WARN[0000] The "DATABASE_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DJANGO_ALLOWED_HOSTS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEBUG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONTEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONTEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONTEND_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_PORT" variable is not set. Defaulting to a blank string. 
no port specified: :<empty>

**Comment by to-sta** [comment]
There is an error in the .gitignore file btw.: You are declare `.env` file to be ignored and in the next line you are saying keep it with `!.env`

I will close the PR @bharath637462.

**Comment by bharath637462** [comment]
@to-sta 
when i run above command i get 

permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dactivist-bharath%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied



i got this error

**Comment by to-sta** [comment]
@bharath637462 this error is not related to the env file.

**Pull request closed without merging**
