### PR TITLE
Add and remove links from connect card

### PR DESCRIPTION
**Pull request by messiuw**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

Changes introduced in this pull request adress the issue [#154](https://github.com/activist-org/activist/issues/154). It is now possible to add and remove contacts. Smoke tests have been performed.

### Related issue

- #154

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @messiuw! This is generally working really well 😊 If I delete an account it won't let me enter it in again, but then this is fine as this part of it will be being handled by the backend anyway. My one question is why Flowbite needed to be added in. Is it possible to use [HeadlessUI](https://headlessui.com/) for similar use cases?

**Comment by andrewtavis** [comment]
And no stress about the merge conflicts! I'd be happy to deal with those :)

**Comment by messiuw** [comment]
Thanks for your Review! I mainly added flowbite because I saw that the UI uses tailwind and flowbite is supposed to be designed on top of tailwind. If you rather would like to use headless UI I can check if this will work as well. I'm always eager and happy to learn something new, so if this is not time critical I can check :)

**Comment by andrewtavis** [comment]
Happy to review, @messiuw! It's not time critical as of now, and if you could check switching it to Headless UI that'd be great :) That components framework is directly from the makers of Tailwind, and I'd prefer to keep our dependencies reliant on as few and as large of dev communities as we can 😊 

Thanks so much!

**Comment by messiuw** [comment]
Hi @andrewtavis! I pushed some changes with respect to your most recent comment. Have a look and let me know what you think :) Sorry for the long waiting time, I was quite busy at work these days.

**Pull request merged**
