### PR TITLE
Issue Resolved : Add missing image alt texts for localization (#405)

### PR DESCRIPTION
**Pull request by hariFED**
### **Description**
Add image alt texts to the en-US.json file to enable localization.

### **Related Issue**
Resolves [#405](https://github.com/activist-org/activist/issues/405)

### **Motivation and Context**
There are alt texts in the codebase that are currently hard-coded and not localized. This pull request aims to fix this issue by adding the missing alt texts to the en-US.json file, allowing for proper localization.

### **Changes Made**

- Added new keys-value pairs to the en-US.json file for each missing alt text.
- Modified the codebase to utilize the new keys using the $t() syntax.

### **How to Test**

- Check that the en-US.json file now contains the added keys and corresponding alt texts.
- Verify that the codebase is updated to use the $t() syntax for alt texts.
- Test the application's functionality and ensure that the images display the correct alt texts based on the selected language.

### **Checklist**

- [ ]  Self-reviewed my own code
- [ ] Ensured that the code follows the project's coding standards and style guidelines
- [ ] Verified that all tests pass successfully

**_Additional Notes_**

Please review this pull request and provide any feedback or suggestions. I'm happy to address any concerns or make further improvements if needed.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thank you, @hariFED! Looking forward to checking this out :) I'm a bit ill at the moment, so it will be a few days, but I appreciate you getting to this so quickly! 🙏

**Comment by hariFED** [comment]
Thank you so much for your quick response. I really appreciate it! Take your time and don't worry about the delay, your health comes first. I hope you get well soon. Looking forward for the feedback about the code changes  when you're feeling better. Thanks again for assigning me in this issue.

**Review by andrewtavis — APPROVED** [review]
This all looks really great, @hariFED 😊 

I seem to have messed something up when fixing the merge conflicts, but I'll figure it out on my end! I switched over [activist.org/about](https://activist.org/about) to be an index page, so that lead to some conflicts with this, but should be easy enough. 

I'll merge, and the expectation will be that it won't deploy, but I'll follow it up shortly with the needed fixes to get this done 🚀 Thanks for the work here! Sorry that the review took a bit of time. Have been a bit sick and needed to rest :)

**Comment by hariFED** [comment]
I am happy to rework on this issue as it's just the path need to be changed and some changes i json file. Any way Happy to contribute to your project 😊.

**Pull request merged**
