### PR TITLE
added orgs to populate db management command, improved org factory

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
I have added the organizations to the populate db command. 

WIP: 
* org_text needs to be added to the OrganizationFactory
* Events should be added
* Group should be added

### Related issue

- #938

### CODE REVIEW

**Comment by to-sta** [comment]
I removed the StatusType query within the OrganizationFactory and switched to factory_boy implementation. This we are removing the need of db access for fixtures.

**Comment by andrewtavis** [comment]
I've reduced the number of entities/users/events created to 10 as the frontend build speed is faster, and everything's running in parallel now, so the frontend was actually loading faster than the backend with 100 (and even 50).

**Comment by andrewtavis** [comment]
This still needs work to get the tests running, and the organization text table isn't returning a description – navigating to `/organizations` doesn't work as descriptions aren't coming through.

**Review by andrewtavis — APPROVED** [review]
Thanks so much @to-sta, @momanyisamuel and @wkyoshida!

**Pull request merged**
