### PR TITLE
Feature/icon conversion

### PR DESCRIPTION
**Pull request by otaree**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Improved Icon Consistency: Adopted standard icons (e.g., Bootstrap Icons) for non-branded elements. Enhanced maintenance by removing IconLegal and IconDiscussion.

### Related issue

- #303

### CODE REVIEW

**Comment by andrewtavis** [comment]
The commit messages here are a bit messy, @otaree. I'm not 100% sure about it, but I think that some of the commits will get repeated by this. I know it's super late on your end, and I'm currently working on something really large to finalize #288. Would you want to wait for that to come through tonight and then make a new PR tomorrow where first you pull the new changes, then make the changes for the issue, and then send something fresh?

**Comment by andrewtavis** [comment]
Changes themselves look great though! I just don't want the commits to get weird 😇

**Comment by andrewtavis** [comment]
Tons of changes for localization just went through, @otaree 😊 With that being said, would likely be best if this is re-implemented so we can start fresh from the current state. If you can clean the commit history for this PR, then I can take a look again, but also feel free to close this one and open a new one with the changes applied to the current state of the repo :)

**Comment by otaree** [comment]
Thank you for the update! Given the extensive localization changes, I believe it's best to create a fresh pull request. I'll prepare a new one with the updated changes aligned to the current state of the repository. I'll ensure the commit history is cleaned up before submitting.

Appreciate your guidance!

**Comment by andrewtavis** [comment]
Thank you for the quick update here, @otaree! Really is gonna make reviewing this much easier 😊😊 Appreciate your consideration here :)

I’ll close this given #313 🙌

**Pull request closed without merging**
