### PR TITLE
 Create/apply margin spacing and style classes #83 

### PR DESCRIPTION
**Pull request by momanyisamuel**
added 

  .responsive-px-2 {
    @apply px-6 lg:px-8 xl:px-10
  }
  .responsive-px-4 {
    @apply px-6 lg:px-10 xl:px-14
  }
  .responsive-py-2 {
    @apply py-6 lg:py-8 xl:py-10
  }
  .responsive-py-4 {
    @apply py-6 lg:py-10 xl:py-14
  }

### CODE REVIEW

**Comment by andrewtavis** [comment]
So far looks really good, @momanyisamuel! Could you add one more custom class to this that basically combines the ones we use for header sizing into one?

**Comment by momanyisamuel** [comment]
Hi @andrewtavis i added 

.responsive-h1 {
    @apply py-2 lg:py-4 xl:py-6 text-2xl sm:text-3xl md:text-4xl xl:text-5xl
  }
  .responsive-h2 {
    @apply py-2 lg:py-4 xl:py-6 text-xl sm:text-2xl md:text-3xl xl:text-4xl
  }
  .responsive-h3 {
    @apply py-1 lg:py-2 xl:py-4 text-lg sm:text-xl md:text-2xl xl:text-3xl 
  }

for the headers

**Comment by andrewtavis** [comment]
This all looks great, @momanyisamuel. Can you add the `yarn.lock` back in though? I'm pretty sure that's what's making the Netlify tests fail :)

**Review by andrewtavis — APPROVED** [review]
Really great, @momanyisamuel! As I said, I really like the naming criteria that you used for all of this. I think it's really gonna help us improve the readability and consistency of the code base 😊 Thanks for the efforts and the quick reactions to comments!

**Pull request merged**
