### PR TITLE
 Add transition to sidebar collapse #68 

### PR DESCRIPTION
**Pull request by momanyisamuel**
added `transition-all duration-700` to Sidebar, SidebarFooter,SidebarHeader,SidebarMainSectionSelectors and home
also added flex property to center collapse button

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thank you, @momanyisamuel! If the explanation I gave for the components in #68 is enough to work more, then feel free to continue to send along commits :) Really happy about the progress here 😊

**Comment by andrewtavis** [comment]
Hey @momanyisamuel! Let me know how you want to proceed on this issue 😊 Happy to take a look myself :) We're getting to a point where we want to start using the sidebar in some of the directory pages like for the docs, so my focus is going to switch over to finalizing the sidebar soonish :)

**Comment by momanyisamuel** [comment]
Okay so i think its a CSS only issue that requires a different styling strategy so I have been testing different ways to deal with it lemme finalize today and we can discuss

**Comment by momanyisamuel** [comment]
Hi @andrewtavis so sorry for the delay. I think the solution would be to add a delay using the Vue <Transition> component I am not too familiar with VueJs so kindly assist from here. Also for the logo the view box size is too large and causing an issue during the transition.
had no access to the figma file otherwise i would have fixed the icon and logo sizes - I can assist with this just reach out on Matrix

**Comment by andrewtavis** [comment]
How do the logo sizes need to be fixed, @momanyisamuel? Would be happy to do that myself. As of now we're keeping the public designs locked, but there are private designs I could give access to some point (there mostly just sketches of things we could do before they're moved to the public ones).

**Comment by momanyisamuel** [comment]
So basically if the logo is occupying a space of lets say `140px` by `50px` then the SVG logo exported should have a `viewBox` similar to this i.e - `viewBox = <min-x> <min-y> <width> <height>` thus ` viewBox ="0 0 140 50" width="140" height = "50" `. With this you could actually pan or zoom to just the first letter/logo-mark instead of hiding and showing two different SVG's
see here - https://webdesign.tutsplus.com/tutorials/svg-viewport-and-viewbox-for-beginners--cms-30844
you can easily fix this in Figma and ensure you are exporting the correct SVG check here - https://levimcg.com/blog/more-control-over-figma-svg-exports/

**Comment by andrewtavis** [comment]
Sorry for the late reply. I do have the `viewBox` constrains in as you described, but maybe the issue is that I have the SVGs as components rather than just as the SVG files themselves? So within [SidebarHeader](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarHeader.vue) we're referencing `IconsActivist` or `LogosActivist`, where these might need to just be SVGs within `public`? Should I switch that around?

It  makes sense that we should just pan in on the image so just the `a` shows rather than replacing it though 😊 Good idea :)

**Review by andrewtavis — APPROVED** [review]
@momanyisamuel, I'm really happy with the progress on this so far regardless of the minor issues from the component/SVG functionality 😊 I'm going to transfer the above comments into the issue, and then we can make some micro tasks to handle all the work that needs to be done :) I feel like the stuff that needs to be done is now more component/SVG based rather than the transition itself.

**Pull request merged**
