### PR TITLE
#681/feature create modal share page v2

### PR DESCRIPTION
**Pull request by GrandSuccess87**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

The purpose of this merge request is to share activist pages to various social media platforms (Telegram + Twitter + Mastodon) as well as via Email.  The user also has the option to copy and paste info (name of event/organization + url) to their clipboard to share via SMS or however else they'd like and they can also download the QR Code. 

I forked the activist repo and developed and tested on my feature branch in my forked repo: GrandSuccess87/activist-TA 

Test actions:
1. Run `docker compose up --build`
2. Visit `http://localhost:3000/en/organizations/1/about` or `http://localhost:3000/en/events/1/about`
3. Click "Share Organization" / "Share Event"

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @GrandSuccess87 👋 Sorry this week has been a long one. We should be good to go here. No stress on your end :) 

I'll try to get to it soon so we can move on to other share methods!

**Comment by andrewtavis** [comment]
Frontend formatting check fail is a known issue where precommit and prettier aren't agreeing by the looks of it (#740).

**Review by andrewtavis — APPROVED** [review]
All's looking amazing here, @GrandSuccess87! I'll do some minor edits here so that we have icons coming from icones being passed in rather than their paths, but aside from that this is great! Will write in the issue after the fact! Let's also keep in mind that you could potentially use a break from the share component, but also just let me know how you're doing for it 😊

**Comment by GrandSuccess87** [comment]
Wonderful! It's officially complete, such a great feeling! :D I'll check out some of the other open issues and circle back around with you!

**Pull request merged**
