### PR TITLE
feat(component): Created calendar input using vcalendar library

### PR DESCRIPTION
**Pull request by rohram04**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Created a calendar input form using the vcalendar library as discussed in #169. The API Request needs to be adjusted once a corresponding backend endpoint is created and a calendar to display the events is being made. In it's current form **this is not complete or ready to be merged**. I am looking for input as I develop the component. The changes have been tested using the following [CodeSandbox Environment](https://codesandbox.io/p/sandbox/late-firefly-t2llp4?file=%2Fsrc%2Fcomponents%2FCalendar.vue%3A5%2C18)

### Related issue

- #169

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @rohram04 👋

Thanks for the PR here :)

Not sure if you can see the deploy log, but the error here is the following:

```
[vite]: Rollup failed to resolve import v-calendar from /opt/build/repo/frontend/components/Media/Calendar.vue.
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by rohram04** [comment]
> Hey @rohram04 👋
> 
> Thanks for the PR here :)
> 
> Not sure if you can see the deploy log, but the error here is the following:
> 
> ```
> [vite]: Rollup failed to resolve import v-calendar from /opt/build/repo/frontend/components/Media/Calendar.vue.
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> ```

That's odd I made sure to install the package. Let me look into it. In the meantime if you want to check out the component you can visit [CodeSandbox](https://codesandbox.io/p/sandbox/late-firefly-t2llp4?file=%2Fsrc%2Fcomponents%2FCalendar.vue%3A5%2C18) and run `npm run dev`

**Comment by andrewtavis** [comment]
Hey @rohram04! Finally have some time to get to some of these PRs :) How are you doing on this? Do you need some help getting Docker setup for yourself?

Overall comments: as I said in the dev sync it's really looking good. I would maybe style it such that the time selection is on the same row rather than one on top of the other (we can do one on top of the other for mobile as we'll have less space).

**Comment by rohram04** [comment]
> Hey @rohram04! Finally have some time to get to some of these PRs :) How are you doing on this? Do you need some help getting Docker setup for yourself?
> 
> Overall comments: as I said in the dev sync it's really looking good. I would maybe style it such that the time selection is on the same row rather than one on top of the other (we can do one on top of the other for mobile as we'll have less space).

Hello, I had some issues using docker. Docker itself is setup but when I run docker-compose up the backend runs fine but the frontend produces the following error log;

`
2023-07-25 08:29:35 Nuxi 3.6.2
2023-07-25 08:29:35 Nuxt 3.6.2 with Nitro 2.5.2
2023-07-25 08:29:36 
2023-07-25 08:29:36   > Listening:    http://localhost:3000/ 
2023-07-25 08:29:36 
2023-07-25 08:29:37 ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
2023-07-25 08:29:38 ℹ Tailwind Viewer: http://localhost:3000/_tailwind/
2023-07-25 08:29:45 [nitro] [uncaughtException] Error: listen EADDRINUSE: address already in use /tmp/nitro/worker-39-1.sock
2023-07-25 08:27:01 
2023-07-25 08:27:01  ERROR  Failed to load url /node_modules/dist/vue-i18n.mjs (resolved id: /app/node_modules/dist/vue-i18n.mjs). Does the file exist?
2023-07-25 08:27:01 
2023-07-25 08:27:05 
2023-07-25 08:27:05  ERROR  Failed to load url /node_modules/dist/vue-i18n.mjs (resolved id: /app/node_modules/dist/vue-i18n.mjs) in /app/node_modules/@nuxtjs/i18n/dist/runtime/plugin.mjs. Does the file exist?
2023-07-25 08:27:05 
2023-07-25 08:27:06 
2023-07-25 08:27:06  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Menu/MenuMeatball.vue". Does the file exist?
2023-07-25 08:27:06 
2023-07-25 08:27:06 
2023-07-25 08:27:06  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Selector/SelectorLanguage.vue". Does the file exist?
2023-07-25 08:27:06 
2023-07-25 08:27:06 
2023-07-25 08:27:06  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Sidebar/SidebarFooter.vue". Does the file exist?
2023-07-25 08:27:06 
2023-07-25 08:27:07 ✘ [ERROR] Could not read from file: /app/node_modules/dist/vue-i18n.mjs
2023-07-25 08:27:07 
2023-07-25 08:27:07     node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14:
2023-07-25 08:27:07       10 │ export * from 'vue-i18n'
2023-07-25 08:27:07          ╵               ~~~~~~~~~~
2023-07-25 08:27:07 
2023-07-25 08:27:07 
2023-07-25 08:27:07  ERROR  error while updating dependencies:
2023-07-25 08:27:07 Error: Build failed with 1 error:
2023-07-25 08:27:07 node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14: ERROR: Could not read from file: /app/node_modules/dist/vue-i18n.mjs
2023-07-25 08:27:07     at failureErrorWithLog (/app/node_modules/vite/node_modules/esbuild/lib/main.js:1636:15)
2023-07-25 08:27:07     at /app/node_modules/vite/node_modules/esbuild/lib/main.js:1048:25
2023-07-25 08:27:07     at /app/node_modules/vite/node_modules/esbuild/lib/main.js:1512:9
2023-07-25 08:27:07     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-25 08:27:07 
2023-07-25 08:29:43 
2023-07-25 08:29:43  ERROR  Failed to load url /node_modules/dist/vue-i18n.mjs (resolved id: /app/node_modules/dist/vue-i18n.mjs). Does the file exist?
2023-07-25 08:29:43 
2023-07-25 08:29:47 
2023-07-25 08:29:47  ERROR  Failed to load url /node_modules/dist/vue-i18n.mjs (resolved id: /app/node_modules/dist/vue-i18n.mjs) in /app/node_modules/@nuxtjs/i18n/dist/runtime/plugin.mjs. Does the file exist?
2023-07-25 08:29:47 
2023-07-25 08:29:48 
2023-07-25 08:29:48  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Selector/SelectorLanguage.vue". Does the file exist?
2023-07-25 08:29:48 
2023-07-25 08:29:48 
2023-07-25 08:29:48  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Menu/MenuMeatball.vue". Does the file exist?
2023-07-25 08:29:48 
2023-07-25 08:29:48 
2023-07-25 08:29:48  ERROR  Failed to resolve import "/app/node_modules/dist/vue-i18n.mjs" from "components/Sidebar/SidebarFooter.vue". Does the file exist?
2023-07-25 08:29:48 
2023-07-25 08:29:49 ✘ [ERROR] Could not read from file: /app/node_modules/dist/vue-i18n.mjs
2023-07-25 08:29:49 
2023-07-25 08:29:49     node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14:
2023-07-25 08:29:49       10 │ export * from 'vue-i18n'
2023-07-25 08:29:49          ╵               ~~~~~~~~~~
2023-07-25 08:29:49 
2023-07-25 08:29:49 
2023-07-25 08:29:49  ERROR  error while updating dependencies:
2023-07-25 08:29:49 Error: Build failed with 1 error:
2023-07-25 08:29:49 node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14: ERROR: Could not read from file: /app/node_modules/dist/vue-i18n.mjs
2023-07-25 08:29:49     at failureErrorWithLog (/app/node_modules/vite/node_modules/esbuild/lib/main.js:1636:15)
2023-07-25 08:29:49     at /app/node_modules/vite/node_modules/esbuild/lib/main.js:1048:25
2023-07-25 08:29:49     at /app/node_modules/vite/node_modules/esbuild/lib/main.js:1512:9
2023-07-25 08:29:49     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-25 08:29:49 
2023-07-25 08:29:45     at Server.setupListenHandle [as _listen2] (node:net:1757:21)
2023-07-25 08:29:45     at listenInCluster (node:net:1822:12)
2023-07-25 08:29:45     at Server.listen (node:net:1921:5)
2023-07-25 08:29:45     at file:///app/.nuxt/dev/index.mjs:3848:8
2023-07-25 08:29:45     at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
2023-07-25 08:29:45   code: 'EADDRINUSE',
2023-07-25 08:29:45   errno: -98,
2023-07-25 08:29:45   syscall: 'listen',
2023-07-25 08:29:45   address: '/tmp/nitro/worker-39-1.sock',
2023-07-25 08:29:45   port: -1
2023-07-25 08:29:45 }
2023-07-25 08:29:49 ℹ Vite client warmed up in 9005ms
2023-07-25 08:29:50 [nitro] ✔ Nitro built in 1756 ms
`

It says it's missing some modules. I'm going to look into it myself but just wanted to see if you have seen this before and have any ideas for dealing with it?

**Comment by andrewtavis** [comment]
Updated your comment so there’s formatting for the code, @rohram04 :) Will take a look into it!

**Comment by andrewtavis** [comment]
@rohram04, glad that Docker is generally working except for this error :) Some suggestions I have:

- Try `docker-compose up --build` instead
- Remove the `.nuxt` folder from `/frontend` and run `docker-compose up --build`
- If you're using Docker Desktop, delete the container and run `docker-compose up --build`

Let me know if any of these help :) I'm hopeful that just the first one will get us to a working build 😊

**Comment by andrewtavis** [comment]
@rohram04, quick note that in #240 the components directory you're committing to was renamed `media` from `Media` to better fit Nuxt standards :) Let's keep this in mind. 

Let me know if there's anything else I can do to help!

**Review by andrewtavis — APPROVED** [review]
Hey there @rohram04 👋 Appreciate the work here. I'll bring it in at this point and will work to finish it in the coming weeks :)

**Pull request merged**
