### PR TITLE
#86 fixed logo and search transitions

### PR DESCRIPTION
**Pull request by connorlunsford**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

- fixed padding on search bar changing when sidebar transitions
- Added separate transitions to search input and shortcuts to stop clipping
- Changed logo/icon size and style to transition nicer

### Related issue

- #86

### CODE REVIEW

**Comment by connorlunsford** [comment]
@andrewtavis, tell me what you think. Not super happy with the icon -> logo transition. I made it so the icon always stays there and the logo just fades in to make it more cohesive. However the icon and logo don't match up 100% so it gets a little thicker as it transitions. Could fix by changing the image unless you can find another way but any way I tried looks a little jarring.

Let me know what you think and feel free to tag me in any other issue you think I can handle. Thanks!

**Comment by andrewtavis** [comment]
Sorry for taking a bit to get to this, @connorlunsford! Has been a very busy week for me :) Checking the [deploy preview](https://deploy-preview-100--activist-org.netlify.app/) I'm seeing both the icon and the logo as well as box around the search bar icon 🤔 I've learned recently in #49 that the deploy preview is going to be what it is that we're getting, regardless of if the behavior we're seeing within a docker run looks fine.

I also agree that the transition isn't ideal... Do you want to check out the [icon designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?node-id=10%3A18&t=OPwgkJGmzFlTeJdl-1) and let me know what you'd need me to make to have this working the way you'd like it to? Would be happy to export whatever you need for this!

**Comment by connorlunsford** [comment]
@andrewtavis no worries at all. I'm fairly busy too so this pace works well for me! I didn't notice the box around the search bar too, I'll fix that in a push later today.

In terms of fixing the logo, the options are not optimal in my opinion and I'm not sure if I know enough to figure out how to fix it in the "best" way. These are the options I'm thinking about.
1. Create an icon that's an exact copy of the a in the logo (important part would be the exact same spacing on the top and left side as the logo) so that even though the logo and icon exist at the same time, they overlap without notice.
2. Create a logo that is a copy of the current logo, but without the a (so just "ctivist") and then the a won't overlap at all. I like this better than 1 but it's still not great.
3. Figure out another transition. I've tried a couple different options but all of them just don't look great. Fading in the logo and fading out the icon at the same time creates this weird overlap effect. Hard cut looks far too jarring. I'm not a huge design guy so I would love some help if you had any ideas for a way we can do this well. Thanks!

**Comment by andrewtavis** [comment]
Hey @connorlunsford! I like the ideas! 😊 Let me toy around with it a bit, but either of the options would at least be better than what we have now. Exporting things so they’re exactly what we need is easy enough :)

**Review by andrewtavis — APPROVED** [review]
Hey @connorlunsford! I'm gonna bring this in and play around with it a bit more with some others changes I'm going to be making 😊 Will try to figure out the logo transition myself, but will check in for your feedback. I'll be posting a bunch of issues in the coming days as well :) Let me know if you have interest in any of them!

**Pull request merged**
