### PR TITLE
add card org application vote

### PR DESCRIPTION
**Pull request by rigojr**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- Add the org application vote
- To test the feature use the following [http://localhost:3000/en/organizations/123/about?status=pending](http://localhost:3000/en/organizations/123/about?status=pending)
- A temporal param has been added for testing purpose, it'll remove as soon as the required information is available

Notes:
- The component has `upVotes` and `downVotes`, those are `ref` variable for testing purpose, this information should came as props.
- An event mechanism should be set between the component an their clients in order to communicate up and down votes, the `click` event could be forwarded.
- In the list of favor organizations, where the organization's icon is being shown, a better scope should be defined.
  - What happen if an organization do not have an icon set?
  - Should we limit this list to only 3 organizations? following the figma example?
  - How should we sort those organization display? what should be first and last?
- The disabled option need to be added in the `btnLabeled` component.
- Change made in `about.vue` for testing purpose should be removed.
 
Screen Capture
image

### Related issue

- #462

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thank you, @rigojr! I'll get to this soon 😊 Really happy to have this feature 🥳

**Comment by rigojr** [comment]
Hi @andrewtavis I believe I could improve this implementation. Nevertheless, I would like to expand the information about it's scope, let me know what do you think about those notes I post in the description of the PR.

Apart of that what is the purpose of the `ariaLabel`? and the property `supporters` in `Organization` answer to what?

**Comment by andrewtavis** [comment]
Answers to some of your questions, @rigojr 😊

> In the list of favor organizations, where the organization's icon is being shown, a better scope should be defined.
> - What happen if an organization do not have an icon set?

Would just be the default organization icon that we have.

> - Should we limit this list to only 3 organizations? following the figma example?

No the list shouldn't be limited. Maybe after a certain number of organizations we'd show more and then we can see a modal or expand the field to show all? Do you have any suggestions?

> - How should we sort those organization display? what should be first and last?

First organization is the first to upvote, and they'd follow in order from there :)

> The disabled option need to be added in the btnLabeled component.

Makes sense so we can disable the vote buttons! You'd be welcome to add this in here, but also I can add it after merging.

> Apart of that what is the purpose of the `ariaLabel`?

`ariaLabel` should be setting the `aria-label` for a11y for screen readers. I'm assuming you mean for the buttons? Is this not what you're seeing?

> and the property `supporters` in `Organization` answer to what?

Supporters is similar to say a follower on another platform. You'd get notifications from organizations and statements from the organization would also go out to you. When an organization comes onto the platform we'd want all organizations that have voted for it to automatically be supporters. This is also something for us to keep track of on the community end of things as if we see that an organization is being problematic and further that all of its original supporters are not supporting anymore, then it'd be a good indication that something's not right.

Let me know if you have further questions!

**Comment by rigojr** [comment]
Hi Andrew, I just uploaded a final version of this PR, some key points I'd like to mention.
- I remember for the last tech sync we had that the organization status would be held by the PostgreSQL with numbers, we should add an `enum` to express that status in good type terms. It'll avoid future problems. Can you list me the possible options an organization status could have? I can add it.
- About the maximum count of organizations, I believe that the best approach is to limit to a certain number that depends on the device the web app is being shown since the screen could be larger or smaller, the number of organizations available for the first view should be limited by that number, we can add at the end of that list the organization icon with a bubble contained number (Like the red number that we had in iPhone when an application has notifications) in the upper right corner of the icon.
- I noticed that the `IconOrganization` doesn't support the dark theme.
- The vote button is being resized when the inner count changes, we should take care of that in the future.
- We could improve the `up-vote` and `down-vote` with two-way binding. However, I don’t think we should since the voting process could interact with external and probably async artifacts, so I’ll advise waiting.

I can take care of those things I noticed, no problem, I just want to let you know.

For finishing, some capture
**6 organizations with defined icons**
image

**15 organizations with defined icons, only 10 are visible, for now**
image

**6 organizations with undefined icons**
image

** 15 organizations with undefined icons, only 10 are visible**
image

**card org application vote component in about page when query param is not defined**
image

**Comment by andrewtavis** [comment]
Hey @rigojr 👋 Thanks for the continued work here! Answers to your questions:

> Can you list me the possible options an organization status could have? I can add it.

They could be 1: Pending or 2: Accepted. We're encoding 1 with the defaults always, with the default being Pending and 2 is the only other option, which would mean that enough organizations have expressed interest in them coming on. We might do 3: Declined, but that's up for continued conversation and it sounds like from the sync it's not a priority to make a final decision on including it or not. Your feedback on whether we'd close an application or not would be welcome! Obviously not deleting the application, but whether we'd ever say "No" rather than "Looks like there's no interest" as a community.

> About the maximum count of organizations, I believe that the best approach is to limit to a certain number that depends on the device the web app is being shown...

Completely agree!

> I noticed that the IconOrganization doesn't support the dark theme.

It does! You just need to use `dark:fill-light-text` and it should work :) Hopefully we can change these later such that we can just use the text property for them, but as of now it's an SVG that's called like an icon, so we need to use `fill`.

Thanks for the other suggestions!

A final thing, can we put a light border around the images thats `border-light-section-div dark:border-dark-section-div`? That way if there is a white background we'll still see the organizations as squares in a similar way that we see the contributor GitHub icons on the [supporters showcase](https://activist.org/en/supporters/showcase).

Looking forward to the final review and the merge! 🚀

**Comment by andrewtavis** [comment]
Quoting myself:

> Hopefully we can change these later such that we can just use the text property for them, but as of now it's an SVG that's called like an icon, so we need to use `fill`.

If you have some ideas on this it'd be great! Would be an issue I'd be happy to make and maybe you could work on it :)

**Comment by rigojr** [comment]
Howdy, @andrewtavis 
- The `dark:fill-light-text` didn't work for me, I used `dark:fill-white` is that ok?.
image
image
- in other PR I'll add an `enum` for the Organization types and related refactors.
- I add `border rounded border-light-section-div dark:border-dark-section-div`
image
image

> If you have some ideas on this it'd be great! Would be an issue I'd be happy to make and maybe you could work on it
I'll think about it, I don't have a solution right away, We should keep it under the radar.

**Comment by andrewtavis** [comment]
Thank you, @rigojr! Looks like we're ready for a review here :) I can see if I can figure out why the `dark-text` isn't working on my end, but regardless I'll try to bring this in by end of week 😊

**Review by andrewtavis — APPROVED** [review]
Looking great here, @rigojr! Really happy to have had you working on this. I'll bring it in and see if I can figure out the `dark:fill`, but aside from that we're looking great as far as the component is concerned. I think for the future we should redirect to the application in case the organization is pending, but we can check that out later 😊

Will write in the issue when I'm all done!

**Pull request merged**
