### PR TITLE
Added app shield component

### PR DESCRIPTION
**Pull request by esslamben**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Sorry for the delay, been busy with work and new spiderman. I've not written vue before so please let me know if I've made a mess of anything. The shield component you had already had the styles I needed so I copied it to a more generic component and updated the styles a bit to make it more responsive as part of a bigger grid. I did notice on the figma link that the boxes dont line up so I went with that first but it really didn't look good on the site itself. So instead made them all the same width and they collapse to 2 cols at sm & 1 col at xs. Only issue I had is I don't think coreui has an f-droid icon so I'll wait to hear how you want to handle that. I left a commented out div on the landing page so that you could test it

Screenshot 2023-10-21 at 23 14 17
Screenshot 2023-10-21 at 23 14 05
Screenshot 2023-10-21 at 23 14 11

-->

### Related issue

- #464

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks @esslamben! I'll give this a look in the coming days :) :)

**Comment by andrewtavis** [comment]
Hey @esslamben! Everything here's looking really good :) I'd be happy to merge and do the minor fixes that need to be done, but wanted to check to see if you wanted to work on them yourself. Big thing is that we're never going to have all six of these shields in one place, as seen on the [landing page designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=517%3A3258&mode=design&t=AlLbh8Ypbk4y2hMx-1). We'll have the app ones on the left and the GitHub ones on the right :) They definitely should be the same width, but would you be willing to refactor the new grid so that it's only the ones for apps? We'd also need to edit the L10N keys such that we again have a separate section for the GitHub shields and the app shields 😊

Let me know how all this sounds!

**Comment by andrewtavis** [comment]
Ah, and as far as icons, how about we switch all the icons for the app shields over the [simple icons](https://icones.js.org/collection/simple-icons) and we can use [their F-droid one](https://icones.js.org/collection/simple-icons?s=fdroid) as well?

**Comment by esslamben** [comment]
Sure I can continue on this, its a bit late for me now but I'll take a look tomorrow evening.

1. Update to use simple icons
2. Update grid to only include app ones on the left and github on the right 
3. Sort out the L10N keys so that we can have app shields and github shields

Did I capture all the changes?

**Comment by andrewtavis** [comment]
Almost got it all, @esslamben :)

> 2. Update grid to only include app ones on the left and github on the right

What I mean here is that these shouldn't be in the same component. We should have `GridGitHubShields` and `GridAppShields`, with each having three shields. Mostly you just need to remove the GitHub shields from `GridAppShields` and we'll be good to go 😊

**Comment by esslamben** [comment]
Hey @andrewtavis all those changes are done now. You can see an example in the screenshot below. I removed it from the landing but it can wait till you're ready to use it 🚀 . I'm ready for some other prs if you have more work lined up, really enjoying working on this. 

Screenshot 2023-10-25 at 19 38 04

**Review by andrewtavis — APPROVED** [review]
Looks great, @esslamben! Really looking forward to adding these to the landing page one day 😊😊 Also glad that you're enjoying working on activist! I'll be making more issues in the coming days, and it'd be great to have you continue to work on things here!

**Pull request merged**
