### PR TITLE
[fix] Make safari ios status bar update with theme change #103

### PR DESCRIPTION
**Pull request by DaniKline**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

For Safari in iOS, The color used for the status bar is the background color by default ([link to short article](https://useyourloaf.com/blog/safari-15-theme-color/), [link to Apple dev forum thread](https://developer.apple.com/forums/thread/683403)). Following the instructions on those links, I added additional meta tags in nuxt.config.ts to include theme-color for the light and dark themes. When running locally on my PC (viewed in Chrome) this addition doesn't change anything (expected behavior). After I open the PR, I'll check the Netlify preview to confirm the effect for Safari in iOS is as expected.  

 

### Related issue

- #103

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thinking about it a bit more @DaniKline, maybe something we need to consider is to update the part of tailwind.css that defines the background color and simply apply a "content" (white or off-black) background color in all the components we want to be those colors 🤔 It's a bit of work, but it might be the only way we're going to get the color to switch properly. Line is here:

https://github.com/activist-org/activist/blob/b71f35954914586505873cb232ff1bb824f9d098/frontend/assets/css/tailwind.css#L7

What do you think about this? Would you have interest in going through and adding `bg-light-content dark:bg-dark-content` to some components so they maintain their current colors?

**Comment by DaniKline** [comment]
I took too long to write this so I saw your comment part way through. I'm gonna leave it though for easy reference and reply to your comments separately. 

#### Previews in Safari
- The status bar **does not** update on theme selection. It requires the page be refreshed to update. 
##### Dark Mode
- The status bar color matches the color of the header when theme selection is dark mode. 
- The status bar color matches the color of the header when the theme selection is system 


##### Light Mode
- The status bar color **does not** match the color of the header when theme is light mode. It is the dark mode header color. 


- The status bar color matches the color of the header when the theme selection is system. 

#### Production Site Screenshots for Reference


From left to right: Safari Dark Mode, Safari Dark Mode switched from Light Mode with no refresh, Safari Light Mode, Chrome Dark Mode, Chrome Light Mode. 
- Chrome only changes the address bar & status bar from system settings & the colors do not match that of the header. 
- In Safari, the status bar color **does not** match the color of the header when theme is dark mode, but it does change between dark and light when the themes are selected **and** when the theme is set to system after a refresh.

**Comment by DaniKline** [comment]
> Thinking about it a bit more @DaniKline, maybe something we need to consider is to update the part of tailwind.css that defines the background color and simply apply a "content" (white or off-black) background color in all the components we want to be those colors 🤔 It's a bit of work, but it might be the only way we're going to get the color to switch properly. Line is here:
> 
> https://github.com/activist-org/activist/blob/b71f35954914586505873cb232ff1bb824f9d098/frontend/assets/css/tailwind.css#L7
> 
> What do you think about this? Would you have interest in going through and adding `bg-light-content dark:bg-dark-content` to some components so they maintain their current colors after we switch the above line to `bg-light-header dark:bg-dark-header`?

That makes sense! I'm happy to give that a try. Thank you for the help (and the patience).

**Comment by andrewtavis** [comment]
Thank you for your help! And also thanks for the documentation of your thoughts 😊 Let me know if you have any questions on what should get `bg-light-content dark:bg-dark-content` assigned, but I guess you can see it on the website as well :) Happy to help look for where the color should be assigned if the divs are a bit too nested :)

**Comment by andrewtavis** [comment]
@DaniKline, I did some edits in 3c9c991 as I'm realizing that asking you to go through the entire project and make sure the backgrounds maintain the current colors is a bit of an ask for what should be a `good first issue` 😊 After these changes I think we should be good to go by just reverting the edits to `nuxt.config.ts` and then make the changes to the background colors in `layer base` of [frontend/assets/css/tailwind.css](https://github.com/activist-org/activist/blob/main/frontend/assets/css/tailwind.css). Let me know if this sounds alright and feel free to send the change along if so!

Hope you're well! :) :)

**Comment by DaniKline** [comment]
Sounds good! I can get that done today. Apologies for the wait & thank you!

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Just marking the PR as a request for changes so that I can keep track of all the PRs going on, @DaniKline. With the code night we're doing tonight there should be a lot more :) Happy to have this hopefully figured out! 🥳

**Comment by andrewtavis** [comment]
Hey there @DaniKline 👋 Checking in to see how you're doing with this. Let me know if I can support in any way :)

**Comment by DaniKline** [comment]
Hi @andrewtavis , unfortunately I have a critically ill family member and have been away from nearly everything in the mean time. I am expecting to be back on Sunday. I am so sorry for the lack of communication.

**Comment by andrewtavis** [comment]
@DaniKline, appreciate your willingness to share your situation with me. Really don’t worry about being away - under your circumstances especially. I’m one to know that it’s hard to talk about stuff around the time when a family member is Ill. Wishing you and your family the best at this time, and feel free to check in when you can on this :)

**Review by andrewtavis — APPROVED** [review]
@DaniKline, I hope it's ok if I go ahead and make the change myself. I'm trying to shift to other parts of the project and would like to be able to clear my head on this :) I'll merge this so you get the credit for the change, and then will come in and revert the change and try what we'd discussed. 

Wishing you the very best, and I hope you contribute again in the future! You're more than welcome to take future issues :)

**Pull request merged**
