### PR TITLE
Activist 278: Mobile pages from events and organizations

### PR DESCRIPTION
**Pull request by felipolis**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

I worked on the development of the /events/[id] and /organizations/[id] pages.

Initially, I focused on the page redirection logic. Now, if the user's screen width is less than or equal to 384 pixels (as per the tailwindcss definitions), the user will stay on the /event/[id] or /organizations/[id] page. Otherwise, they will be automatically redirected to the /event/[id]/about or /organizations/[id]/about pages.

Furthermore, I added the display of the image, title, subtitle, and buttons related to organizations or events on their respective pages. For the implementation of these buttons, I used the MenuLinkWrapper component.

### Related issue

- #278

### CODE REVIEW

**Comment by felipolis** [comment]
Hey @andrewtavis, could you take a look?

**Comment by andrewtavis** [comment]
Yes can do, @felipolis! Thanks for working on this! Really exciting to get this set up :)

Will likely end up being tomorrow, but I’ll be in touch 😊

**Comment by felipolis** [comment]
Happy to help! Thanks a lot!

**Comment by andrewtavis** [comment]
Quick note on this, @felipolis: I think that we want the mobile navigation page to show up beneath the small breakpoint, so `640px` based on [Tailwind screen sizes](https://tailwindcss.com/docs/screens) rather than `348px` :) Small includes tablets as well, where the next one medium is more for tablets in landscape mode and small desktops.

Could you make this quick change and I'll finalize the review? 😊

**Comment by felipolis** [comment]
No problem. @andrewtavis !! I agree, I was doubtful about that size... I already fixed it :D

**Review by andrewtavis — APPROVED** [review]
Thanks for the work here, @felipolis! I'll merge this in and send a few minor changes to close up #278 :) :) Seems to be that some of the options are not being disabled even if they're active. Will figure that out quickly and then we'll be good to go! 🚀

**Pull request merged**
