### PR TITLE
923 - Modal still open ...

### PR DESCRIPTION
**Pull request by mattburnett-repo**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR addresses issue 923. The changes affected modal components that use an 'isOpen' prop; the 'isOpen' props and related functionality were removed.

Modals related to Organizations were affected. Other entities (ie Events) were not checked.

Testing was done following the original description of the problem in issue 923 (click activist icon, use forward / backward arrows to navigate, etc.). However, there appears to be an error with reloading the organization data when clicking the back button to check if modal is not displayed, so we can't be completely sure that everything is fixed.

That being said, the affected modals appear to work correctly without the 'isOpen' props, meaning that they appear to operate normally.

### Related issue

- #923

### CODE REVIEW

**Comment by andrewtavis** [comment]
One question on this, @mattburnett-repo: What the purpose of all the `Watch for closeModal emit and do cleanup when it happens.` in the codebase now? Can we remove these somehow? And can we clean up the command palette code a bit to remove the TODOs from it? Maybe you could let me know what issues could be made from those TODOs, and then I can make the issues and we can remove the comments?

**Comment by mattburnett-repo** [comment]
The 'Watch for closeModal emit...' are there just in case they are needed in the future. If you prefer, they can be removed.

The TODO messages in the command palette are notes-to-self. Later this evening I will go through them and let you know which of these are issue-relevant.

**Comment by mattburnett-repo** [comment]
Here's a list of issues from the TODO's removed from ModalCommandPalette.vue

Search works, but it's picking up the literal values of 'displayName' (eg. "_global.home"). Search should instead look through the rendered values.

Sometimes router.push() loses the i18n part of the path (eg: /en/the.path.name)

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @mattburnett-repo! Sorry for the wait in bringing this in... Let me know what your thoughts are on the next steps for modals :) Really is great that you're focusing in on them so much with them being such a large part of the UX 😊

**Pull request merged**
