### PR TITLE
[fix] Make docs buttons equal widths #82

### PR DESCRIPTION
**Pull request by 1shubhankar9**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

Using the style property to apply inline CSS styles to the button element. The width property is set to 200px to give the button a fixed width of 200 pixels.

The buttons are changed for 

- frontend/pages/docs/get-active.vue
- frontend/pages/docs/get-organized.vue
- frontend/pages/docs/grow-organization.vue

This is how the buttons looks(Website)
image

This is the button(mobile)
image

### Related issue

- #82

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hey @1shubhankar9 👋 Thanks for the PR! The [deploy preview](https://deploy-preview-106--activist-org.netlify.app/en/docs/get-active) seems to not have the behavior that's displayed in your images as the request access button has its text split over two lines. See below:

Screenshot_2023-05-01 22 08 17

Also activist uses [Tailwind CSS](https://tailwindcss.com/) for styling, so it'd be great if you could convert the `style="width: 200px;"` lines to `class="w-52"`, with `w-52` corresponding to `208px` in the [Tailwind width properties](https://tailwindcss.com/docs/width). You might need to make it a bit wider like `w-56` to make sure that the text is on one line, but I'll leave that to you to figure out the proper dimensions 😊

**Comment by andrewtavis** [comment]
Note also @1shubhankar9 that one way to do this would also be to set the width of the `Return home` button via a reference to the width of the `Request access` button :) This likely would be the best solution to this as we wouldn't need to worry about changing the button sizes if say another language has longer text (a later step would be to compare which has a longer text and set the other one to its width, which we could maybe do after this one 🚀). Happy to provide some resources for this if you'd like some direction. Was just thinking about it and decided to share how I'd do this 😇

**Comment by andrewtavis** [comment]
Hey @1shubhankar9 :) Checking in with you on how the edits are coming. You’re also welcome to do the baseline changes that switch over the styling to Tailwind and I’ll do the comparison of the widths after :) Let me know if you need further support or have any questions! Happy to help 😊

**Comment by 1shubhankar9** [comment]
@andrewtavis On it something urgent came up I'll try to raise PR soon again

**Comment by andrewtavis** [comment]
No stress, @1shubhankar9! Just checking in :) Last thing that I want is for you to be confused and feel that you can’t reach out for help 😊 Hope all’s well!

**Comment by andrewtavis** [comment]
Hey @1shubhankar9 👋 Checking in with you to see if I can help in any way. I'm really happy to take care of the merge conflict for you, so no stress on that :) Also again totally fine to send along a basic fix like the one described in the [comment above](https://github.com/activist-org/activist/pull/106#pullrequestreview-1408070595) 😊

**Comment by andrewtavis** [comment]
@1shubhankar9, I'm going to merge as is and make the change to add in the `w-56` for Tailwind as we discussed :) Would like to have this finished 🙃 Thanks for the initial changes and your contributions!

**Pull request merged**
