### PR TITLE
feat: add transition to hidden hotkey indicators

### PR DESCRIPTION
**Pull request by TeddyGavi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

1. Add `transition-opacity transition-duration-200` to the hotKeyIndicators `div`
2. modify the existing CSS conditional `.hide` class from `display: none;` to `opacity: 0;`
3. Remove `focus:w-5/6` from parent input as it was causing a slight layout shift during the transition

Before:
beforeHotkey

After:
afterHotkeyChanges

Layout Shift:
layoutshiftissue

### Related issue

- #125

### CODE REVIEW

**Comment by andrewtavis** [comment]
Woooot first code committt 🙌 Thanks @TeddyGavi! Will check it later tonight odds are 😊 Excited to have another issue done to get this sidebar looking better and better :)

**Comment by TeddyGavi** [comment]
@andrewtavis I am not 100% sure about this solution! I am sure there is another way. I am new to Vue. My experience has been primarily in Nextjs and React. I am excited to learn and continue to contribute. :smiley:

**Comment by andrewtavis** [comment]
At this stage it doesn't have to be perfect, @TeddyGavi :) I'm also learning Vue/Nuxt myself. We just need to keep at it and slowly more folks will join to exchange ideas and expertise 😊

**Comment by andrewtavis** [comment]
One thing @TeddyGavi :) We actually do need `focus:w-5/6` or a similar style added in as this allows the user to type almost the full length of the search bar. As it is now the search text only fills half of the search bar before it starts to overflow. Aside from that all's wonderful! 🥳 Super smooth timing and just feels great :)

**Comment by TeddyGavi** [comment]
@andrewtavis Ok! I will look into this layout shift further.

**Comment by andrewtavis** [comment]
Thank you, @TeddyGavi! 😊

**Comment by samcdonovan** [comment]
Hey @TeddyGavi, I just wanted to chime in a bit here because I was the one that originally added the code to hide the hotkeys. I tried adding an animation to it much in the same way you have done, but found that using 'opacity: 0' meant that the input bar would not extend to its full length (because the hotkeys container was still affecting the document flow). That's why I used 'display: none' which allowed the input to extend to its full length, but because of the way the 'display' property works, it meant that the animation no longer worked properly. Just thought I'd give a little bit of my thought process around that :)

**Comment by andrewtavis** [comment]
Thanks for giving these insights, @samcdonovan!

**Comment by TeddyGavi** [comment]
Thank you for sharing @samcdonovan I didn't mean to step on any toes here. I believe I figured out a solution. It involves adding both `display: none;` and the conditional class of `.hide` to control the opacity. 

When search input is focused, immediately apply `.hide` aka `opacity: 0;` (with transition) and after a delay of 200ms apply `focus:w-5/6` to input and also at the same time `hidden` aka `display: none;` to the hotkey indicators (to allow for the search input to take up 83.3% of the width :) ). 

when blurred, immediately remove `hidden` and `focus:w-5/6`, then after a 200ms delay remove `.hide`. This is the same logic but in reverse.

 A new commit is incoming. Let me know what you think. I am sure there is a better way and something I missed :thinking:

**Review by andrewtavis — APPROVED** [review]
Changes all look good and the functionality is exactly what we're looking for, @TeddyGavi 😊 Thanks for this! 🌙🥳

**Pull request merged**
