### PR TITLE
Feature: created GridGitHubContributors custom component

### PR DESCRIPTION
**Pull request by luuu-xu**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Created `GridGitHubContributors` component which fetches and displays full list of our GitHub contributors, including their avatar images, their log-in IDs, and links externally to their GitHub profile page.

### Related issue

- #231

### CODE REVIEW

**Comment by andrewtavis** [comment]
Nice, @luuu-xu! Looking forward to checking this out :) :)

**Comment by andrewtavis** [comment]
Hey @luuu-xu! This is looking awesome 😊 One quick question: why is it only doing the top 30 contributors? Would be great if we could figure it out such that it's all of them :)

**Comment by luuu-xu** [comment]
> why is it only doing the top 30 contributors?

@andrewtavis Huh, great catch! I didn't think of it, I thought the API response is everyone we have. I will look into it now. Design and feature wise, or a11y side, do you have any additional ideas?

**Comment by andrewtavis** [comment]
Design and feature wise all’s great, @luuu-xu 😊😊 My only comment would be maybe we want a `section-div` border around the circles in case someone has a white/black background. I can also look at it myself post merge 🙃

And the idea of adding a more button in there for future requests is good with me :) This would extend it, or change the first 30 to the next 30? Extending’s perfect in my opinion :) I’m thinking this might be better anyway as originally we’d need to load them all, which would reduce page response times. Also on mobile it’s already going to extend for quite a few page heights.

**Comment by luuu-xu** [comment]
@andrewtavis Hi, I have added the load more button and I have also added a `section-div` border to the avatar, which is a great design point! Thank you!

By the way, I will be going on a trip tomorrow so I wouldn't have time to work on our project for three weeks. But I can definitely join our discussions!

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @luuu-xu! Totally amazing 🤩 I'll update the [development channel](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) with this now for sure 😊

Minor thing that I'll do is make sure that we have the `Load more` text in the localization strings, but aside from this it's perfect 🥇🏆

**Comment by andrewtavis** [comment]
Hope you have a great time on your trip, btw! Sad to hear that you won't be able to make it to Code Night 🌙 on Saturday, as there's lots of folks from the team who'd like to meet you (me included 🙃). Safe travels, and I appreciate that you're willing to continue to join in the discussions while you're gone!

**Pull request merged**
