### PR TITLE
BugFix: Eslint rules does not gives warning for VS Code

### PR DESCRIPTION
**Pull request by ahmedy00**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #445

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @ahmedy00 👋 Thanks for this! 😊 Don't forget to fill out your [PR description](https://github.com/activist-org/activist/pull/448#issue-1943136825) as this can help others who might want to review and aren't exactly sure what the context is :) More of a problem for the future, but good to get into the practice now 😇

**Comment by andrewtavis** [comment]
This solves the issue that the error isn't showing up, @ahmedy00 😊 Issue is that the dev env really starts screaming issues at me including the `module.exports` one in `eslintrc`. Are you still getting this error? I feel like this is likely a Nuxt issue? Should we try [nuxt/eslint-config](https://github.com/nuxt/eslint-config/tree/main)? If so, would we need `eslint-plugin-vue`, or would that be optional potentially?

**Comment by ahmedy00** [comment]
> This solves the issue that the block order error isn't showing up, @ahmedy00 😊 Issue is that the dev env really starts screaming issues at me including the `module.exports` one in `eslintrc`. Are you still getting this error? I basically have an error in every `.vue` file when I check this out.
> 
> I feel like this is likely a Nuxt issue? Should we try [nuxt/eslint-config](https://github.com/nuxt/eslint-config/tree/main)? If so, would we need `eslint-plugin-vue`, or would that be optional potentially?

**Comment by andrewtavis** [comment]
Let me think on this @ahmedy00 and see if adding the Nuxt eslint plugin would solve these errors :)

**Review by andrewtavis — APPROVED** [review]
Hey @ahmedy00, we'll be merging in #452 right after this that sends along new configuration files and fixes a ton of the errors we were seeing 😊 Thanks for the initial work on this! 🚀

**Pull request merged**
