### PR TITLE
 Fix sidebar icon positioning #107 

### PR DESCRIPTION
**Pull request by momanyisamuel**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

- to ensure all icons on `Sidebar` are centered introduced css classes `basis-full justify-center gap-1` to `menuSelector`
- wrapped the `menuSelector` icon in a span and also wrapped both the `menuSelector` icon and text in a div similar to `sidebaFooter` -> `DisclosureButton`
- applied a basis to both the icon and text in `menuSelector`
- applied similar styles to `sidebaFooter` as those in `menuSelector` list 
- this was tested by applying outlines on `menuSelector` and related parent elements to ensure all items were centered correctly.

### Related issue

- #107

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thank you, @momanyisamuel! I'll check this out later :) :)

**Comment by andrewtavis** [comment]
Quick comment on this, @momanyisamuel :) The icons in the main section selector seem to be inline with the ones in the footer, but all of them seem to still be a little bit over to the left 🤔 What I'm seeing is that we have a space between the icon and the word that would be displayed if the sidebar was expanded, and this space is still being accounted for when it's compressed. As we need the icon to stay in one place as the word is extended, maybe what makes sense is to just put a space before the icons as well? We can then maybe reduce the x-padding if it's not what we need. What do you think? 😊

**Comment by momanyisamuel** [comment]
@andrewtavis The spacing while expanding was being caused by the basis property actually. the icon was growing to occupy the space being left when the text is removed on collapse. i changed this to width and it seems to maintain position. let me know what you think.

**Review by andrewtavis — APPROVED** [review]
Looks wonderful, @momanyisamuel! Thanks for coming through again with some great work! 🙏 Plus with the most recent version the little jump that was happening in the text reveal of the main section selectors is gone. Super happy 😊

**Pull request merged**
