### PR TITLE
Fix: Updated package.json inclusion of Vite and Vue

### PR DESCRIPTION
**Pull request by arescrimson**
Updating Vite and Vue versions here will prevent frontend errors. Vue and Vite versions confirmed through project Vite and Vue versions.

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This change is to resolve issue #643, where contributing developers, upon docker container startup, would see many error logs from unmet peer dependencies. This was because Vite/Vue versions were not specified in the `package.json` file. 

This was fixed by first checking Vite/Vue versions that Activist is currently using. 

image

Before adding these in, these errors would be logged. 

image

After, this fix removes the aforementioned errors from logging. 

image

This PR will also not include `yarn.lock` - that should update on its own. Let me know if anything needs to be changed, however ;DD

### Related issue

- #643

### CODE REVIEW

**Comment by arescrimson** [comment]
Interesting; looks like TypeScript checks are failing on two files: `SidebarRight` and `MenuSearchResult`. @andrewtavis, any thoughts? We took a look at both quite recently, so was wondering what could have happened.

**Comment by andrewtavis** [comment]
One thing that might be happening is that the types have been updated given the explicit inclusions of these dependencies. Not really sure though as I haven't touched these recently aside from maybe some localization key changes. Do you want to fix these, or should I? Totally fine either way! :)

**Comment by arescrimson** [comment]
What I thought too; introducing new dependencies like this could have more impact outside of squashing these error logs, but I do find it interesting since we literally just worked on both of these files. Could look more into this, looks like some simple typescript changes so I'll see what I can do and test if it fixes it :)) Of course if you see what's wrong/ what needs be changed feel free to edit/let me know.

**Comment by andrewtavis** [comment]
Thanks for looking into this, @arescrimson! The check should handle most of the changes, so I wouldn't worry too much about something outside of it. Ideally you would also see these as errors in the files now, and you should also see it locally by running `yarn nuxi prepare` and `yarn nuxi typecheck` in the `frontend` directory to prepare he TS types and check the frontend :)

**Comment by arescrimson** [comment]
Cool! Tested out one final change and it looks like this one could work. Basically, TypeScript is expecting a object value here for `onClickOutside`, and we are providing it with `quickActionBtnAndMenu`. Since this is a reference to the `ref()` object, we get this type mismatch error. However, if we instead pass in `quickActionBtnAndMenu.value`, it looks like it fixes it, and will do so for the other file as well. Will confirm this in the morning!

**Comment by andrewtavis** [comment]
Are we good for a final review here, @arescrimson?

**Comment by arescrimson** [comment]
@andrewtavis Yep!

**Review by andrewtavis — APPROVED** [review]
Thanks for the research and the implementation, @arescrimson! Glad to have these errors figured out 😊 Just a few more and the dev experience will be where it needs to be :)

**Pull request merged**
