### PR TITLE
746: create upload modal

### PR DESCRIPTION
**Pull request by bozmen**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #768

### CODE REVIEW

**Comment by bozmen** [comment]
Still a lot to do. This is my PR just playing around with things.

- [ ] Style properly
- [ ] Use translation for labels
- [ ] Actually make it do things (connect it to the backend)

**Comment by andrewtavis** [comment]
Hey @bozmen 👋 FYI we're ordering the Tailwind classes a bit differently with a plugin rather than an extension. Hence the merge conflict odds are :) I can take care of this, if need be 😊

**Comment by bozmen** [comment]
@andrewtavis You mean how they are ordered in the class?

**Comment by andrewtavis** [comment]
It was actually a really easy one, @bozmen :) The order of height and width classes switched in the new update, and you had a change that maintained the old order in one place. We're good to go after 40ad9d7!

**Comment by andrewtavis** [comment]
Fuck, sorry. Apparently fucked up the change...

**Comment by andrewtavis** [comment]
Alright, we're good as far as merge conflicts now 😊 There are some prop ordering issues and a few other minor changes that the frontend check is picking up, but those should be pretty standard to fix. Would be happy to see the progress in the dev sync, if you're planning on being there!

**Comment by andrewtavis** [comment]
A note from @therealhoppi (your old coworker) on this, if it's possible to include a ordering mechanic to this, it'd be great. With this being said, don't worry about it and we can make another issue. Let's keep this mind for the current development though :)

**Comment by andrewtavis** [comment]
Heyo @bozmen 👋 FYI I updated the dependencies, so we have some conflicts now. Let me know if there's anything I can do to help, and also happy to jump on a call!

**Comment by andrewtavis** [comment]
Quoting the above:

> Still a lot to do. This is my PR just playing around with things.
> 
> * [ ]  Style properly
> * [ ]  Use translation for labels
> * [ ]  Actually make it do things (connect it to the backend)
> * [ ]  Handle auth

I'll handle the first two and we can get to the other two in #839 :)

**Comment by andrewtavis** [comment]
Merge conflicts for `yarn.lock` were solved by dropping the most recent version in... I'll rebuild the dependencies and push a new version of it. Might be merging on failed tests because of it, but so it goes 🤷‍♂️

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @bozmen! Need to bring this in so that I can work on the strong dependencies of all of the modals. The merge conflicts were gonna get nuts without bringing this in first. Further work for validating for the frontend can be done in a new issue, and the other points you brought up can be handled by #839.

Really appreciate the care that went into this 😊 So amazing, especially given you weren't even working from designs :) :)

**Pull request merged**
