### PR TITLE
Initial Resource API setup 🎅🎁🎄 

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

In this PR, I have started implementing the first API for the Resource table. I had to make some changes to the table in order to make the privat field useful. I added the created_by to implement the logic for GET requests. 

In case a user is the creator for a resource and the privat field is set to True, the creator should still be able to retrieve the resource. Permissions are set to `IsAuthenticatedOrReadOnly`. 

Additionally, I have deleted a few validation utility functions inside the serializer, because the model itself already provided sufficient validation.

`GET, POST, PUT, PATCH` methods are setup with the viewset methods. I used the  

Tests have been manually via swagger for all the methods and endpoints that are covered by the ResourceViewSet. I would suggest to create unit tests for API later on, when we think it is stable. 

### Related issue

- #624

### CODE REVIEW

**Comment by to-sta** [comment]
@andrewtavis Could you explain the field total_flags to me? What is it used for and how should it be incremented or set?

**Comment by andrewtavis** [comment]
> @andrewtavis Could you explain the field total_flags to me? What is it used for and how should it be incremented or set?

Hey @to-sta! Thanks for all this :) `total_flags` would be used by people to indicate to use that a resource is problematic. Would be set to 0, and it's incremented by one for each person who flags the resource :)

**Comment by to-sta** [comment]
> Hey @to-sta! Thanks for all this :) `total_flags` would be used by people to indicate to use that a resource is problematic. Would be set to 0, and it's incremented by one for each person who flags the resource :)

hmm if it's only a IntegerField, then are bad actor could incremented this multiple times because we are not keeping a record of who flagged which resource.

**Comment by andrewtavis** [comment]
Very true! Shit. So are we needing a `flag` table then in a similar way that we have the `support` table?

**Comment by to-sta** [comment]
Hmm total_flags is the sum of unique user_id and resource_id. So the table needs at least those two.

We could either query the total_flags or we could increment the total_flags count when an entry is made for the flag table (on save).

**Comment by andrewtavis** [comment]
Thanks @to-sta! I'll also make a quick table in the designs.

**Comment by andrewtavis** [comment]
For here we're good for a review then?

**Comment by to-sta** [comment]
> For here we're good for a review then?

Yeah, all good for the review.

**Comment by andrewtavis** [comment]
Hey @to-sta: FYI I threw together the issue right now as I've been making a bunch of "add table from schema" issues recently anyway 😇

- https://github.com/activist-org/activist/issues/626

Let me know what you think!

**Comment by to-sta** [comment]
@andrewtavis will create Issues for the API's today 😃 and it's great idea if you get some full stack experience. Especially the API design is handy when you work on fetching data later on in the frontend.

@baibhavKumar1 was also interested in working on the upcoming backend issues.

**Comment by andrewtavis** [comment]
All sounds good! For those tagged, please let us know if we should tag you in new issues!

**Comment by baibhavKumar1** [comment]
I am working in backend, and happy to implement sir, but my stack has NodeJS instead of Django.

**Comment by andrewtavis** [comment]
You'd be welcome to give it a try, @baibhavKumar1 :)

**Comment by to-sta** [comment]
@baibhavKumar1 sry my fault, I tagged the username :sweat_smile: should have been @bharath637462

**Comment by bharath637462** [comment]
hi @to-sta fianlly a task from backend what should i do come on come on

**Comment by rigojr** [comment]
Happy to help, let me know if an API ticket is free for me. I'm about to start working on https://github.com/activist-org/activist/issues/620

CC: @andrewtavis  @to-sta

**Pull request merged**
