### PR TITLE
Replace useUniqueId for uuid package

### PR DESCRIPTION
**Pull request by rigojr**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- Remove `UseUniqueID` composable for [uuid](https://www.npmjs.com/package/uuid) package.
- When removing `UseUniqueID` composable, a minor memory leak inserted by the use of global variable is deleted `let UUID = 0`.

### Related issue

- No formal issue related, it was talk here https://github.com/activist-org/activist/issues/260#issuecomment-1732129561

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thank you @rigojr! I need to sleep, but I'll check this out in the coming days :)

**Review by andrewtavis — APPROVED** [review]
Appreciate you following through on this, @rigojr! Perfect to have someone in the community who's taking these sorts of things seriously and will make a note to make sure they get done 🙏

**Comment by andrewtavis** [comment]
Hey @rigojr 👋 I was getting some TS errors where `uuid` wasn't being found, so based on some research I changed the way that the imports were working. Can you check and let me know if the changes make sense? 🙏

**Comment by andrewtavis** [comment]
Note that my fix is incorrect as we can't use `require` with Vite :) I'll look into a fix 🙃

**Comment by andrewtavis** [comment]
ef49f8e reverted back the change and added in `// @ts-nocheck` to the `<script>` block. Definitely not ideal, but then https://github.com/nuxt/nuxt/issues/13040 and the linked https://github.com/unjs/nitro/issues/87 don't seem to be resolved. Maybe I'm unclear on this though and there is a work around. Would appreciate if you can figure out an solution, @rigojr! I didn't want those nicely typed form components to suddenly have an error 😇

**Comment by rigojr** [comment]
@andrewtavis  what TS issue did you face?

**Comment by andrewtavis** [comment]
Cannot find module `uuid` of its corresponding type declarations :)

Screenshot_2023-10-11 22 56 04

**Comment by rigojr** [comment]
@andrewtavis that is weird, `"@types/uuid": "^9.0.5"` should make the work. What Vue extensions do you have ?

Also I noticed that I added `uuid` as a `dev-dependencies` it should be `dependency` required in production. I'll make that change tonight, sorry for that mistake.

**Comment by andrewtavis** [comment]
No need for an apology whatsoever, @rigojr :) The extensions I'm using are the ones we have [in the readme](https://github.com/activist-org/activist#environment-setup) (plus a couple others). Maybe getting it in as a `dependency` would help. Let's check in later after that change goes through :)

**Comment by rigojr** [comment]
@andrewtavis just to let you know, I'm little bit busy this weekend. I'll let you know as son as I made those changes.

**Comment by andrewtavis** [comment]
No stress whatsoever, @rigojr! I hope the weekend goes well :) And thanks for the consideration here 🙏

**Pull request merged**
