### PR TITLE
Throttle test

### PR DESCRIPTION
**Pull request by sulabhkatila**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Added tests for API rate throttling

### Related issue

- #505

### CODE REVIEW

**Comment by to-sta** [comment]
@sulabhkatila I gave it a test. Started docker and ran pytest. I get the following:

```bash
E       assert 200 == 429
E        +  where 200 = <Response status_code=200, "application/json">.status_code
E        +  and   429 = status.HTTP_429_TOO_MANY_REQUESTS
```
I do get the 429 response from the` test_anon_rate_throttle()` function.

**Comment by to-sta** [comment]
@sulabhkatila there is throttling not being set globally with the default throttling settings in settings.py. As soon as I add throttling_classes to the view it works. 

```python
class ResourceViewSet(viewsets.ModelViewSet[Resource]):
    queryset = Resource.objects.all()
    serializer_class = ResourceSerializer
    pagination_class = CustomPagination
    throttle_classes = [AnonRateThrottle]
```

If you want to continue to work on this, this would be a workaround for testing your implementation. I will have a look into, why throttling is not set globally to everyview by default.

**Comment by sulabhkatila** [comment]
> @sulabhkatila throttling is not being set globally with the default throttling settings in `settings.py`. As soon as I add `throttling_classes` to the view you are testing. It works.
> 
> ```python
> class ResourceViewSet(viewsets.ModelViewSet[Resource]):
>     queryset = Resource.objects.all()
>     serializer_class = ResourceSerializer
>     pagination_class = CustomPagination
>     throttle_classes = [AnonRateThrottle]
> ```
> 
> If you want to continue to work on this, this would be a workaround for testing your implementation. I will have a look into, why throttling is not set globally to every view by default.
> 
> Any ideas @momanyisamuel?

Thank you, I will use this while I try and complete the tests

> ```python
> class ResourceViewSet(viewsets.ModelViewSet[Resource]):
>     queryset = Resource.objects.all()
>     serializer_class = ResourceSerializer
>     pagination_class = CustomPagination
>     throttle_classes = [AnonRateThrottle]
> ```

Thanks, I will use this while I try and complete the tests

**Comment by andrewtavis** [comment]
Hey @sulabhkatila 👋 Thanks for all the work here! We'll do a final check of this tomorrow during a call @to-sta and I have planned :)

**Comment by to-sta** [comment]
@andrewtavis we can merge 😃

**Review by andrewtavis — APPROVED** [review]
Ah ok, I'm seeing that the workflow errors are actually from prior introduced ones for the frontend formatting that are coming up now that we've solved #602. Thanks for the work here, @sulabhkatila, and thanks for the finishing touches, @to-sta!

**Pull request merged**
